#!/usr/bin/env python3
import json
doc = json.load(open('/home/quant/quant-platform/reports/axis_screens/perpdex_funding.json'))
print("axis:", doc.get('axis'))
print("mechanism_class:", doc.get('mechanism_class'))
print()
for i, cell in enumerate(doc.get('screen_outputs', [])):
    print(f"Cell {i}:")
    print(f"  name: {cell.get('name')}")
    print(f"  symbol: {cell.get('symbol')}")
    print(f"  venue: {cell.get('venue')}")
    print(f"  resolution: {cell.get('resolution')}")
    print(f"  verdict: {cell.get('verdict')}")
    print(f"  ic: {cell.get('ic')}")
    print(f"  ic_t: {cell.get('current_z')}")
    print(f"  sharpe_momentum: {cell.get('sharpe_momentum')}")
    print(f"  sharpe_reversal: {cell.get('sharpe_reversal')}")
    print(f"  horizon_days: {cell.get('horizon_days')}")
    print(f"  n_eff: {cell.get('n_eff')}")
    print(f"  n: {cell.get('n')}")
    print(f"  decontam_passed: {cell.get('decontam_passed')}")
    print(f"  implausible_leak: {cell.get('implausible_leak')}")
    print(f"  verdict: {cell.get('verdict')}")
    print()