"""EXOGENOUS EVENT LABELS -- so a CPI print stops looking like a liquidation cascade.

THE CONFOUND, in the studies that are already pre-registered and queued. The failed-breakout study
looks for liquidation cascades; the OI-divergence study reads positioning shifts. Neither has any
notion of WHY a move happened. A cascade triggered by a scheduled macro print and a cascade
generated by the book's own leverage structure are the same object to both harnesses — identical
price, identical OI collapse, identical liquidation prints. But only one of them is the mechanism
being tested. The other is the calendar.

That matters in a specific, directional way: **scheduled events cluster the biggest moves**, so an
uncontrolled study preferentially samples them, and its "mechanism" is partly a macro-release
detector wearing a microstructure name. K3 (regime dependence) cannot separate the two, because a
release window is not a regime.

**THE DANGER THIS MODULE INTRODUCES IS BIGGER THAN THE ONE IT REMOVES, AND THAT IS WHY COVERAGE IS
A FIRST-CLASS FIELD.** An incomplete calendar used to exclude "event windows" excludes a BIASED
SUBSET and leaves the researcher believing the remainder is clean. Missing half the CPI prints is
worse than having no calendar at all: with no calendar you know you have not controlled for events;
with a half-calendar you think you have. So every label carries the calendar's own span and
completeness, and `label()` REFUSES to answer outside the covered window rather than returning
"no event" — which is the same absence-reads-as-clean defect (WS-005) the desk keeps finding.

WHAT IS SEEDED HERE AND WHAT IS NOT. Only events whose dates are STRUCTURALLY determined and
independently checkable are hardcoded: Bitcoin halvings, which are block-height events. Macro
release dates (FOMC, CPI, NFP) are NOT hardcoded, because writing a schedule from memory would
manufacture exactly the false-completeness this module warns about. They load from a JSON file the
operator populates from the publishing authority — free, published in advance, and citable.
"""

from __future__ import annotations

import json
from bisect import bisect_left
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CALENDAR_FILE = ROOT / "data" / "event_calendar.json"

#: Default window either side of an event. 60 minutes is a research default, not a law: a scheduled
#: print moves the book within seconds, but the liquidation cascade it triggers unwinds over
#: minutes to hours, and the cascade is the thing these studies measure.
DEFAULT_WINDOW_MIN: float = 60.0

#: STRUCTURAL events only -- block-height determined, independently verifiable, no schedule to go
#: stale. Deliberately NOT a macro calendar: hardcoding FOMC/CPI dates from memory would create the
#: false completeness this module exists to prevent, and a wrong date is worse than a missing one
#: because it silently mislabels a clean window as contaminated.
_STRUCTURAL: tuple[tuple[str, str], ...] = (
    ("2012-11-28T00:00:00+00:00", "btc_halving"),
    ("2016-07-09T00:00:00+00:00", "btc_halving"),
    ("2020-05-11T00:00:00+00:00", "btc_halving"),
    ("2024-04-20T00:00:00+00:00", "btc_halving"),
)


@dataclass(frozen=True)
class Event:
    ts: datetime
    kind: str
    source: str = "structural"


@dataclass(frozen=True)
class Calendar:
    """Events plus an HONEST statement of what this calendar does and does not cover."""

    events: tuple[Event, ...]
    covered_from: datetime | None
    covered_to: datetime | None
    kinds: tuple[str, ...]
    complete_for: tuple[str, ...] = field(default_factory=tuple)

    def __len__(self) -> int:
        return len(self.events)

    def covers(self, ts: datetime) -> bool:
        """Is `ts` inside the window this calendar claims to know about?

        Outside it the honest answer to "was there an event?" is NOT MEASURED. Returning False
        would let a study treat 2015 as event-free merely because nobody recorded 2015.
        """
        if self.covered_from is None or self.covered_to is None:
            return False
        return self.covered_from <= ts <= self.covered_to


def _parse(s: str) -> datetime:
    d = datetime.fromisoformat(s)
    return d if d.tzinfo else d.replace(tzinfo=UTC)


def load(path: Path = CALENDAR_FILE, *, include_structural: bool = True) -> Calendar:
    """Build the calendar from structural events plus an operator-maintained JSON file.

    File schema (all fields required, so a half-filled row cannot enter silently)::

        {"covered_from": "2019-01-01T00:00:00+00:00",
         "covered_to":   "2026-08-07T00:00:00+00:00",
         "complete_for": ["fomc", "cpi"],
         "events": [{"ts": "...", "kind": "cpi", "source": "bls.gov release schedule"}]}

    `complete_for` is the load-bearing field and it is the operator's ASSERTION, not a computed
    fact: it names the event kinds this file claims to list EXHAUSTIVELY over the covered window.
    A kind absent from that list may appear in `events` and still be incomplete, so a study may
    condition on it but must never claim to have excluded it.
    """
    events: list[Event] = []
    if include_structural:
        events += [Event(_parse(t), k) for t, k in _STRUCTURAL]

    covered_from = covered_to = None
    complete_for: tuple[str, ...] = ()
    try:
        raw = json.loads(path.read_text("utf-8"))
    except (OSError, json.JSONDecodeError):
        raw = {}
    if raw:
        for row in raw.get("events", []):
            try:
                events.append(Event(_parse(row["ts"]), str(row["kind"]),
                                    str(row.get("source", "file"))))
            except (KeyError, TypeError, ValueError):
                continue                      # a malformed row is skipped, never guessed at
        for key, setter in (("covered_from", "from"), ("covered_to", "to")):
            with_val = raw.get(key)
            if with_val:
                try:
                    if setter == "from":
                        covered_from = _parse(str(with_val))
                    else:
                        covered_to = _parse(str(with_val))
                except ValueError:
                    pass
        complete_for = tuple(str(k) for k in raw.get("complete_for", []))

    events.sort(key=lambda e: e.ts)
    # With no declared window, fall back to the events' own span -- but NOT beyond it. A calendar
    # that claimed coverage past its last event would report "no event" for every later timestamp.
    if covered_from is None and events:
        covered_from = events[0].ts
    if covered_to is None and events:
        covered_to = events[-1].ts
    return Calendar(tuple(events), covered_from, covered_to,
                    tuple(dict.fromkeys(e.kind for e in events)), complete_for)


def label(cal: Calendar, timestamps: list[datetime], *,
          window_min: float = DEFAULT_WINDOW_MIN) -> list[str | None]:
    """Per-timestamp label: the event kind in range, ``""`` for none, or ``None`` for NOT COVERED.

    THREE STATES, NOT TWO, AND THAT IS THE WHOLE POINT. ``""`` means "this calendar covers this
    time and there was no event". ``None`` means "this calendar cannot say". Collapsing them into a
    boolean is how an uncovered period gets silently treated as clean, which would make the
    exclusion biased in exactly the direction that flatters the result.
    """
    if not cal.events:
        return [None] * len(timestamps)
    ev_ts = [e.ts for e in cal.events]
    win = timedelta(minutes=window_min)
    out: list[str | None] = []
    for ts in timestamps:
        if not cal.covers(ts):
            out.append(None)
            continue
        i = bisect_left(ev_ts, ts)
        hit = ""
        for j in (i - 1, i):
            if 0 <= j < len(ev_ts) and abs(ev_ts[j] - ts) <= win:
                hit = cal.events[j].kind
                break
        out.append(hit)
    return out


def partition(cal: Calendar, timestamps: list[datetime], *,
              window_min: float = DEFAULT_WINDOW_MIN) -> dict[str, list[int]]:
    """Split indices into ``endogenous`` / ``event`` / ``uncovered``.

    A study reports all three counts. The one that must never be dropped is ``uncovered``: a
    "clean endogenous sample" computed over a period the calendar does not reach is not clean, it
    is unexamined, and reporting it as endogenous is the substitution this desk keeps catching.
    """
    labels = label(cal, timestamps, window_min=window_min)
    out: dict[str, list[int]] = {"endogenous": [], "event": [], "uncovered": []}
    for i, lb in enumerate(labels):
        out["uncovered" if lb is None else ("event" if lb else "endogenous")].append(i)
    return out


def coverage_note(cal: Calendar, parts: dict[str, list[int]]) -> str:
    """The sentence a study must print beside any event-conditioned result."""
    n = sum(len(v) for v in parts.values()) or 1
    unc = len(parts["uncovered"])
    span = (f"{cal.covered_from:%Y-%m-%d} .. {cal.covered_to:%Y-%m-%d}"
            if cal.covered_from and cal.covered_to else "NONE")
    note = (f"event calendar: {len(cal)} events, kinds={list(cal.kinds) or 'none'}, "
            f"span {span}; claimed EXHAUSTIVE for {list(cal.complete_for) or 'NOTHING'}. "
            f"endogenous {len(parts['endogenous'])} / event {len(parts['event'])} / "
            f"UNCOVERED {unc} ({unc / n:.0%})")
    if unc:
        note += (" -- the uncovered bars are NOT known to be event-free; excluding events over a "
                 "partly-covered window removes a BIASED subset and leaves the remainder looking "
                 "clean. Report this split, never just the endogenous arm.")
    if not cal.complete_for:
        note += (" -- NOTHING is claimed exhaustive, so no result here may be described as "
                 "'excluding macro events'; it excludes the events that happen to be listed.")
    return note
