"""Option-chain positioning (QG-OT-005, QG-ADH-001): parser, greeks, PIT, budget, contracts.

No network: the chain is `fixtures/cboe_delayed_options_SPY.json`, constructed in the assumed CBOE
delayed-quotes shape with greeks generated by the module's own Black-Scholes and three tolerance
cases (a contract with no greeks, one with no IV, one undecodable symbol)."""
from __future__ import annotations

import json
import math
import sys
from datetime import UTC, date, datetime, timedelta
from pathlib import Path
from typing import Any

import numpy as np
import pytest

_DESK = Path(__file__).resolve().parents[1]
for _p in (str(_DESK), str(_DESK.parent.parent)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from macro import option_chains as oc  # noqa: E402

from libs.research import sensor_contract as sc  # noqa: E402
from libs.research import sensor_engines as se  # noqa: E402

FIXTURE = _DESK / "tests" / "fixtures" / "cboe_delayed_options_SPY.json"
RECEIVED = datetime(2026, 10, 5, 20, 5, tzinfo=UTC)


def _doc() -> dict[str, Any]:
    return json.loads(FIXTURE.read_text("utf-8"))


# ------------------------------------------------------------------ the TEMPORARY Black-Scholes
def test_bs_put_call_parity_and_gamma_is_the_pdf_not_the_cdf() -> None:
    S, K, T, sig, r, q = 100.0, 95.0, 0.4, 0.3, 0.03, 0.01
    c, p = oc._bs(S, K, T, sig, "C", r, q), oc._bs(S, K, T, sig, "P", r, q)
    assert c is not None and p is not None
    assert c["price"] - p["price"] == pytest.approx(S * math.exp(-q * T) - K * math.exp(-r * T),
                                                    abs=1e-10)
    d1 = (math.log(S / K) + (r - q + 0.5 * sig * sig) * T) / (sig * math.sqrt(T))
    pdf_gamma = math.exp(-q * T) * math.exp(-0.5 * d1 * d1) / math.sqrt(2 * math.pi) / (
        S * sig * math.sqrt(T))
    assert c["gamma"] == pytest.approx(pdf_gamma, rel=1e-12) == p["gamma"]
    # finite difference of delta confirms it; the Q-Fin seeded defect (cdf in place of pdf) does not
    h = 1e-3
    up, dn = oc._bs(S + h, K, T, sig, "C", r, q), oc._bs(S - h, K, T, sig, "C", r, q)
    assert up is not None and dn is not None
    fd = (up["delta"] - dn["delta"]) / (2 * h)
    assert c["gamma"] == pytest.approx(fd, rel=1e-5)
    cdf_gamma = math.exp(-q * T) * oc._ncdf(d1) / (S * sig * math.sqrt(T))
    assert abs(cdf_gamma - fd) > 0.01
    # the donor's put (K e^-rT N(d1) - S N(d2)) breaks parity; ours does not
    d2 = d1 - sig * math.sqrt(T)
    bad_put = K * math.exp(-r * T) * oc._ncdf(d1) - S * oc._ncdf(d2)
    assert abs(bad_put - p["price"]) > 1.0
    iv = oc._implied_vol(c["price"], S, K, T, "C", r, q)
    assert iv == pytest.approx(sig, abs=1e-6)
    assert oc._bs(S, K, 0.0, sig, "C") is None


# ------------------------------------------------------------------ parsing and PIT
def test_parse_fixture_stamps_and_counts() -> None:
    ch = oc.parse_chain(_doc(), etf="SPY", received_at=RECEIVED)
    assert ch["status"] == "PARSED"
    # naive "2026-10-05 15:45:12" is ET (EDT, UTC-4)
    assert ch["quote_time"] == "2026-10-05T19:45:12+00:00" == ch["knowable_at"]
    assert ch["knowable_basis"] == "printed_stamp"
    assert ch["n_skipped"] == 1 and ch["n_parsed"] == 128
    assert ch["greeks_filled"] == {"iv_from_mid": 1, "delta_bs": 1, "gamma_bs": 1}
    assert oc.parse_contract("SPY261016C00570000") == (date(2026, 10, 16), "C", 570.0)
    assert oc.parse_contract("SPXW 261016P05700000") == (date(2026, 10, 16), "P", 5700.0)
    assert oc.parse_contract("SPY261316C00570000") is None


def test_features_on_the_fixture() -> None:
    ch = oc.parse_chain(_doc(), etf="SPY", received_at=RECEIVED)
    out = oc.features(ch)
    f = out["features"]
    assert out["measure"] == "Q" and "LONG calls" in out["dealer_convention"]
    assert out["front_expiry"] == "2026-10-16"          # the 4-DTE expiry is not the front
    assert f["pc_oi_ratio"] > 1.0 and f["pc_volume_ratio"] > 1.0
    assert f["skew_90_110"] > 0.0 and f["rr25"] < 0.0    # the planted put skew
    assert f["atm_iv_front"] == pytest.approx(0.1435, abs=1e-3)
    assert f["atm_iv_30d"] is not None and 0.143 < f["atm_iv_30d"] < 0.148
    assert f["term_slope"] > 0
    assert f["gex"] < 0 and f["gex_sign"] == -1.0
    assert 570.0 < f["gamma_flip"] < 600.0 and f["flip_distance"] > 0
    assert oc._gex(ch["contracts"], f["gamma_flip"], recompute=True) == pytest.approx(
        0.0, abs=abs(f["gex"]) * 0.02)
    assert out["front_strikes"] and all(abs(c["strike"] / 570.0 - 1) <= 0.1
                                        for c in out["front_strikes"])


@pytest.mark.parametrize("doc, why", [
    ([1, 2], "not an object"),
    ({"x": 1}, "no `data`"),
    ({"data": {"options": []}}, "non-empty list"),
    ({"data": {"options": [{"option": "SPY261016C00570000"}]}}, "spot"),
    ({"data": {"current_price": 5, "options": [{"option": "junk"}]}}, "OCC"),
])
def test_parse_failed_is_recorded_never_guessed(doc: Any, why: str) -> None:
    got = oc.parse_chain(doc, etf="SPY", received_at=RECEIVED)
    assert got["status"] == "PARSE_FAILED" and why in got["why"]


def test_pit_falls_back_to_receipt_and_rescales_percent_iv() -> None:
    doc = _doc()
    doc["timestamp"] = "2026-10-05 23:59:00"            # later than receipt: the tz is wrong
    got = oc.parse_chain(doc, etf="SPY", received_at=RECEIVED)
    assert got["knowable_basis"] == "bounded_by_receipt"
    assert got["knowable_at"] == got["received_at"] and "later than receipt" in got["pit_note"]
    doc = _doc()
    doc.pop("timestamp")
    for o in doc["data"]["options"]:
        o.pop("last_trade_time", None)
        if isinstance(o.get("iv"), float):
            o["iv"] = o["iv"] * 100.0
    got = oc.parse_chain(doc, etf="SPY", received_at=RECEIVED)
    assert got["knowable_basis"] == "bounded_by_receipt" and got["iv_unit"] == "percent_rescaled"
    assert max(c["iv"] for c in got["contracts"] if c["iv"]) < 1.0


def test_mapping_resolves_against_the_universe_or_says_not_tradeable() -> None:
    reg = {"US500": {"symbol": "US500"}, "XAUUSD": {"symbol": "XAUUSD"},
           "XTIUSD": {"symbol": "XTIUSD"}, "USDJPY": {"symbol": "USDJPY"}}
    assert oc.resolve(oc.BY_ETF["SPY"], reg)["mt5_symbol"] == "US500"
    assert oc.resolve(oc.BY_ETF["USO"], reg)["mt5_symbol"] == "XTIUSD"
    assert oc.resolve(oc.BY_ETF["FXY"], reg)["orientation"] == -1
    got = oc.resolve(oc.BY_ETF["TLT"], reg)
    assert got["status"] == "NOT_TRADEABLE_HERE" and "UST10Y" in got["tried"]
    real = oc.load_registry()
    if real:                                            # the committed registry, when present
        assert oc.resolve(oc.BY_ETF["GLD"], real)["mt5_symbol"] == "XAUUSD"


# ------------------------------------------------------------------ the organ end to end
def _business_days(n: int, start: date = date(2024, 1, 1)) -> list[date]:
    out, d = [], start
    while len(out) < n:
        if d.weekday() < 5:
            out.append(d)
        d += timedelta(days=1)
    return out


def test_run_budget_lake_ledger_and_unmeasured_contracts(tmp_path: Path) -> None:
    calls: list[str] = []

    def fetcher(etf: str) -> tuple[Any, str]:
        calls.append(etf)
        return (_doc(), "OK") if etf == "SPY" else (None, "FETCH_FAILED: offline")

    reg = {"US500": {"symbol": "US500"}, "XAUUSD": {"symbol": "XAUUSD"}}
    closes = [(d.isoformat(), 100.0 + i) for i, d in enumerate(_business_days(30))]
    ledger = sc.SensorLedger(tmp_path / "sensors")
    kw: dict[str, Any] = {"fetcher": fetcher, "etfs": ["SPY", "GLD", "TLT"],
                          "data_dir": tmp_path / "oc", "registry": reg,
                          "closes_fn": lambda s, n: closes, "vol_index_fn": lambda t: {},
                          "lake_root": tmp_path / "lake", "contracts_root": tmp_path / "c",
                          "ledger": ledger, "report": tmp_path / "R.json", "emit_cells": False}
    doc = oc.run(now=RECEIVED, **kw)
    assert calls == ["SPY", "GLD", "TLT"]
    spy = doc["symbols"]["SPY"]
    assert spy["parse"]["status"] == "PARSED" and spy["lake"]["status"] == "WRITTEN"
    assert doc["symbols"]["TLT"]["mapping"]["status"] == "NOT_TRADEABLE_HERE"
    assert {c["verdict"] for c in doc["contracts"]} == {se.UNMEASURED}
    assert {tuple(c["cards"]) for c in doc["contracts"]} == {("QG-ADH-001",), ("QG-OT-005",)}
    assert doc["ledger"]["appended"] >= 4 and doc["ledger"]["refused"] == 0
    rows = ledger.rows("2026-10-05")
    assert all(r["attributes"]["measure"] == "Q" for r in rows)
    assert all(r["knowable_basis"] == "printed_stamp" for r in rows)
    assert list((tmp_path / "oc" / "SPY").glob("*.json.gz"))
    assert (tmp_path / "R.json").exists() and (tmp_path / "c" / "option_chains.json").exists()
    # the budget: nothing is fetched again inside six hours, everything after
    oc.run(now=RECEIVED + timedelta(hours=5), **kw)
    assert len(calls) == 3
    oc.run(now=RECEIVED + timedelta(hours=6, minutes=1), **kw)
    assert len(calls) == 6
    # dry run writes nothing
    before = sorted(p.name for p in (tmp_path / "oc").rglob("*"))
    oc.run(now=RECEIVED + timedelta(days=2), dry_run=True, **kw)
    assert sorted(p.name for p in (tmp_path / "oc").rglob("*")) == before


def test_cboe_cells_are_terms_held_but_state_is_still_measured(tmp_path: Path) -> None:
    reg = {"US500": {"symbol": "US500"}}
    doc = oc.run(now=RECEIVED, fetcher=lambda e: (_doc(), "OK"), etfs=["SPY"],
                 data_dir=tmp_path / "oc", registry=reg, closes_fn=lambda s, n: [],
                 vol_index_fn=lambda t: {}, dry_run=True)
    assert doc["terms"]["status"] == "HELD"
    assert doc["terms"]["data_source"] == "cboe_delayed:options"
    assert doc["cells"][0].get("emitted", 0) == 0          # held: nothing reaches the registry
    assert doc["symbols"]["SPY"]["latest"]["gex"] < 0      # ...while the state is measured
    clear = tmp_path / "terms_clearances.json"
    clear.write_text(json.dumps({"cboe": {"status": "CLEARED", "by": "terms review",
                                        "terms_url": "https://example.test/terms",
                                        "terms_quote": "machine use permitted"}}), "utf-8")
    assert oc.terms_status(path=clear)["status"] == "CLEARED"
    # the forecast store has no recorded terms basis: the allow-list holds it (audit #211)
    assert oc.terms_status("prediction_markets:forecast_store")["status"] == "HELD"


def test_cell_door_holds_cboe_and_admits_own_bars() -> None:
    got = oc.emit_gated("s", ["a"], ["US500"], data_source="cboe_delayed:options",
                        mechanism="m", falsifier="f", generator="g", dry_run=True)
    assert got["status"] == "HELD_TERMS" and got["emitted"] == 0
    assert oc.emit_gated("s", ["a"], ["US500"], data_source="mt5:bars",
                         mechanism="m", falsifier="f", generator="g", dry_run=True)["emitted"] > 0


# ------------------------------------------------------------------ the GAIN path, synthetic
def _gex_world(n: int, planted: bool, seed: int = 4
               ) -> tuple[list[dict[str, Any]], list[tuple[str, float]]]:
    rng = np.random.default_rng(seed)
    days = _business_days(n)
    neg = np.zeros(n, dtype=bool)
    for i in range(1, n):
        neg[i] = neg[i - 1] if rng.random() < 0.95 else not neg[i - 1]
    rows = [{"available_time": f"{d.isoformat()}T14:00:00+00:00", "gex": -1e9 if neg[i] else 1e9}
            for i, d in enumerate(days)]
    px, prev = [100.0, 100.5], 0.005
    for k in range(2, n):
        eps = rng.normal(0.0, 0.01)
        r = eps + (0.005 * math.copysign(1.0, prev) if planted and neg[k - 1] else 0.0)
        px.append(px[-1] * math.exp(r))
        prev = r
    return rows, [(d.isoformat(), p) for d, p in zip(days, px, strict=True)]


def test_gex_contract_shows_gain_on_a_planted_effect_and_not_on_noise() -> None:
    rows, closes = _gex_world(700, planted=True)
    got = oc.gex_continuation_contract(rows, closes, etf="SPY", symbol="US500")
    assert got["verdict"] == se.GAIN, got
    assert got["continuation_rate_gex_neg"] > got["continuation_rate_gex_pos"]
    assert got["continuation_diff_p_two_sided"] < 0.05
    rows0, closes0 = _gex_world(700, planted=False)
    assert oc.gex_continuation_contract(rows0, closes0, etf="SPY",
                                        symbol="US500")["verdict"] != se.GAIN
    short_rows, short_closes = _gex_world(120, planted=True)
    assert oc.gex_continuation_contract(short_rows, short_closes, etf="SPY",
                                        symbol="US500")["verdict"] == se.UNMEASURED


def _vol_world(n: int, informative: bool, seed: int = 8
               ) -> tuple[list[dict[str, Any]], list[tuple[str, float]], dict[str, float]]:
    rng = np.random.default_rng(seed)
    days = _business_days(n)
    lv = np.zeros(n)
    for i in range(1, n):
        lv[i] = 0.97 * lv[i - 1] + rng.normal(0.0, 0.12)
    sigma = 0.16 * np.exp(lv)
    px = [100.0]
    for i in range(1, n):
        px.append(px[-1] * math.exp(rng.normal(0.0, sigma[i] / math.sqrt(252.0))))
    rows = [{"available_time": f"{d.isoformat()}T14:00:00+00:00",
             "atm_iv_30d": (sigma[i] if informative else 0.16 * math.exp(rng.normal(0, 0.3))),
             "skew_90_110": rng.normal(0.05, 0.01), "pc_oi_ratio": rng.normal(1.2, 0.1)}
            for i, d in enumerate(days)]
    index = {d.isoformat(): 20.0 + rng.normal(0.0, 2.0) for d in days}   # an uninformative index
    return rows, [(d.isoformat(), p) for d, p in zip(days, px, strict=True)], index


def test_vol_forecast_contract_gain_when_the_chain_adds_and_not_otherwise() -> None:
    rows, closes, index = _vol_world(700, informative=True)
    got = oc.vol_forecast_contract(rows, closes, index, etf="GLD", symbol="XAUUSD",
                                   vol_index="^GVZ")
    assert got["verdict"] == se.GAIN and got["relative_reduction"] > 0.2, got
    rows0, closes0, index0 = _vol_world(700, informative=False)
    assert oc.vol_forecast_contract(rows0, closes0, index0, etf="GLD", symbol="XAUUSD",
                                    vol_index="^GVZ")["verdict"] == se.NO_GAIN
    assert oc.vol_forecast_contract(rows[:150], closes[:150], index, etf="GLD",
                                    symbol="XAUUSD", vol_index="^GVZ")["verdict"] == se.UNMEASURED
