"""Tier S layer 16: closure worlds and agent-based worlds, and their join per certificate.

  closure  the market shut and reopened gapped, a session removed for a stretch, an instrument
           halted on stale prints (`libs/tiers/closure_worlds.py`)
  agents   paths generated by momentum, value, noise and liquidity agents
           (`libs/tiers/agent_worlds.py`)

Both families run inside `synthetic_regimes` like every other world (named, seeded, UNMEASURED
when they cannot touch the tape) and are joined per certificate by `tier_s.organ_worlds` the way
the swap world is.
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import pytest

DESK = Path(__file__).resolve().parents[1]
ROOT = DESK.parents[1]
for p in (str(ROOT), str(DESK / "research"), str(DESK)):
    if p not in sys.path:
        sys.path.insert(0, p)

import tier_s as ts  # noqa: E402
from mt5desk.engine import Signal  # noqa: E402

from libs.tiers import agent_worlds, closure_worlds  # noqa: E402
from research import synthetic_regimes as sr  # noqa: E402

N = 3000


def _tape(seed: int = 3, n: int = N) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    idx = pd.date_range("2025-01-06", periods=n, freq="h", tz="UTC")
    close = 1.2 * np.exp(np.cumsum(rng.normal(0, 0.002, n)))
    open_ = np.r_[close[0], close[:-1]]
    hi = np.maximum(open_, close) * 1.001
    lo = np.minimum(open_, close) * 0.999
    return pd.DataFrame({"open": open_, "high": hi, "low": lo, "close": close,
                         "tick_volume": np.full(n, 100.0), "spread": np.full(n, 10.0)},
                        index=idx)


def _rng(seed: int = 1) -> np.random.Generator:
    return np.random.default_rng(seed)


def _ohlc_ok(df: pd.DataFrame) -> bool:
    o, h, lo, c = (df[k].to_numpy() for k in ("open", "high", "low", "close"))
    return bool((h >= np.maximum(o, c) - 1e-12).all() and (lo <= np.minimum(o, c) + 1e-12).all()
                and (lo > 0).all())


# ------------------------------------------------------------------------------ closure worlds

def test_market_closure_removes_the_bars_and_reopens_gapped() -> None:
    bars = _tape()
    out = closure_worlds.market_closure_gap(bars, _rng())
    assert out.applied == closure_worlds.CLOSURE_BARS
    assert len(out.bars) == len(bars) - closure_worlds.CLOSURE_BARS
    idx = pd.DatetimeIndex(out.bars.index)
    hole = int(np.argmax(np.diff(idx.as_unit("ns").asi8)))
    assert (idx[hole + 1] - idx[hole]) == pd.Timedelta(hours=closure_worlds.CLOSURE_BARS + 1)
    gap = abs(np.log(out.bars["open"].iloc[hole + 1] / out.bars["close"].iloc[hole]))
    sd = float(np.std(np.diff(np.log(bars["close"].to_numpy()))))
    assert gap > sd * 3, "the first print after the closure is a gap, not a normal bar"
    assert _ohlc_ok(out.bars)


def test_session_closed_removes_one_session_for_a_stretch_of_days() -> None:
    bars = _tape()
    out = closure_worlds.session_closed(bars, _rng())
    assert out.applied > 0 and len(out.bars) == len(bars) - out.applied
    gone = bars.index.difference(out.bars.index)
    hours = sorted(set(pd.DatetimeIndex(gone).hour))
    assert len(hours) == closure_worlds.SESSION_HOURS
    days = pd.DatetimeIndex(gone).normalize().unique()
    assert len(days) <= closure_worlds.SESSION_DAYS + 1


def test_instrument_halt_prints_stale_then_gaps() -> None:
    bars = _tape()
    out = closure_worlds.instrument_halt(bars, _rng())
    assert out.applied == closure_worlds.HALT_BARS and len(out.bars) == len(bars)
    flat = np.flatnonzero((out.bars["high"] == out.bars["low"]).to_numpy())
    assert len(flat) == closure_worlds.HALT_BARS
    assert (out.bars["tick_volume"].to_numpy()[flat] == 0).all()
    assert np.ptp(out.bars["close"].to_numpy()[flat]) == 0
    assert _ohlc_ok(out.bars)


def test_a_closure_that_cannot_touch_the_tape_says_why() -> None:
    short = _tape(n=100)
    for build in closure_worlds.BUILDERS.values():
        out = build(short, _rng())
        assert out.applied == 0 and out.why


# ------------------------------------------------------------------------------ agent worlds

def test_the_ecologies_generate_the_markets_they_are_named_for() -> None:
    close = _tape(n=6000)["close"].to_numpy()
    got = {}
    for eco in agent_worlds.ECOLOGIES:
        r, why = agent_worlds.agent_returns(eco, close, _rng(4))
        assert not why and len(r) == len(close) and np.isfinite(r).all()
        got[eco.name] = r
    herd, value = got["abm_momentum_herd"], got["abm_value_anchor"]
    assert agent_worlds.autocorr(herd) > 0.2 > agent_worlds.autocorr(value)
    assert agent_worlds.autocorr(value) < 0, "value agents pull the price back"
    thin = got["abm_liquidity_withdrawal"]
    assert np.std(thin) > 1.8 * np.std(value), "withdrawn liquidity: every order moves further"


def test_the_agents_are_seeded_and_calibrated_to_the_tape() -> None:
    close = _tape(n=4000)["close"].to_numpy()
    eco = agent_worlds.BY_NAME["abm_value_anchor"]
    a, _ = agent_worlds.agent_returns(eco, close, _rng(9))
    b, _ = agent_worlds.agent_returns(eco, close, _rng(9))
    c, _ = agent_worlds.agent_returns(eco, close, _rng(10))
    assert np.array_equal(a, b) and not np.array_equal(a, c)
    sd = float(np.std(np.diff(np.log(close))))
    assert 0.7 * sd < float(np.std(a[1:])) < 1.5 * sd
    flat, why = agent_worlds.agent_returns(eco, np.ones(4000), _rng())
    assert why and not flat.any()


# ------------------------------------------------------------------ inside synthetic_regimes

NEW = (*closure_worlds.NAMES, *agent_worlds.NAMES)


def test_both_families_are_scenarios_with_named_failure_modes() -> None:
    for name in NEW:
        assert name in sr.SCENARIOS
    rules = {s for s, _t in sr.FLAG_RULES.values()}
    assert set(NEW) <= rules
    assert sr.FLAG_RULES["halt_fragile"] == (closure_worlds.INSTRUMENT_HALT, "sign")
    assert sr.FLAG_RULES["dies_when_liquidity_withdraws"] == ("abm_liquidity_withdrawal",
                                                              "sign")
    bars = _tape()
    for name in NEW:
        w = sr.SCENARIOS[name][1](bars, "EURUSD", 0, "x")
        assert w.applied > 0, name
        assert _ohlc_ok(w.signal_bars), name
        again = sr.SCENARIOS[name][1](bars, "EURUSD", 0, "x")
        assert w.signal_bars.equals(again.signal_bars), f"{name} is a function of the seed"
    thin = sr.SCENARIOS["abm_liquidity_withdrawal"][1](bars, "EURUSD", 0, "x")
    assert thin.cost_mult == 3.0 and float(thin.signal_bars["spread"].iloc[0]) == 30.0


def _trend_family(df: pd.DataFrame, *, side: int = 1, **_kw: object) -> list[Signal]:
    c = np.asarray(df["close"], dtype="float64")
    out = []
    for i in range(30, len(df) - 20, 12):
        s = 1 if c[i] > c[i - 24] else -1
        out.append(Signal(time=df.index[i], side=s, stop=c[i] * (1 - 0.004 * s),
                          target=c[i] * (1 + 0.006 * s), ttl_bars=12, tag="trend"))
    return out


def test_a_sleeve_is_measured_in_every_closure_and_agent_world(tmp_path: Path,
                                                               monkeypatch: Any) -> None:
    uni = tmp_path / "universe"
    uni.mkdir()
    _tape(n=4000).to_parquet(uni / "TESTSYM_H1.parquet")
    monkeypatch.setattr(sr, "UNIVERSE", uni)
    monkeypatch.setattr(sr, "family_fn", lambda f: _trend_family)
    sleeve = sr.Sleeve("t", "certified", "TESTSYM", "trend", "H1", 1, "", {})
    row = sr.probe_sleeve(sleeve, {}, 5, "minimal_replay", budget_s=600)
    assert "unmeasured" not in row, row
    for name in NEW:
        assert row["scenarios"][name]["status"] == "MEASURED", (name, row["scenarios"][name])


# ------------------------------------------------------------------ joined per certificate

def test_organ_worlds_joins_closure_and_agent_worlds_per_certificate(
        monkeypatch: Any, tmp_path: Path) -> None:
    measured = {"status": "MEASURED", "expectancy": -0.2, "delta_expectancy": -0.5,
                "applied": 48}
    doc = {"scenarios": [{"name": n} for n in NEW],
           "results": [{"symbol": "EURUSD", "family": "f",
                        "flags": ["halt_fragile", "dies_in_herding_market"],
                        "scenarios": {closure_worlds.INSTRUMENT_HALT: measured,
                                      "abm_momentum_herd": measured,
                                      closure_worlds.SESSION_CLOSED: {
                                          "status": "UNMEASURED", "why": "short"}}},
                       {"symbol": "GBPUSD", "family": "f", "flags": [], "scenarios": {}}]}
    monkeypatch.setattr(ts, "_read", lambda p: doc if "SYNTHETIC" in str(p) else {})
    monkeypatch.setattr(ts, "survivors", lambda: {
        "a": {"shadow_spec": {"symbol": "EURUSD", "family": "f"}},
        "b": {"shadow_spec": {"symbol": "GBPUSD", "family": "f"}},
        "c": {"shadow_spec": {"symbol": "USDJPY", "family": "f"}}})
    monkeypatch.setattr(ts, "STATE", tmp_path)
    out = ts.organ_worlds()
    cl, ag = out["closure_worlds"], out["agent_worlds"]
    assert cl["in_synthetic_regimes"] == list(closure_worlds.NAMES)
    assert cl["by_world"][closure_worlds.INSTRUMENT_HALT] == {"MEASURED": 1, "UNMEASURED": 2}
    assert cl["flags"]["halt_fragile"] == 1 and cl["certificates_measured"] == 1
    assert ag["flags"]["dies_in_herding_market"] == 1
    assert out["metric"]["closure_world_measured_share"] == pytest.approx(1 / 3)
    assert out["metric"]["agent_world_measured_share"] == pytest.approx(1 / 3)
    import json
    rows = {r["key"]: r for r in json.loads(
        (tmp_path / "worlds_by_certificate.json").read_text("utf-8"))["rows"]}
    assert rows["a"]["closure_worlds"][closure_worlds.INSTRUMENT_HALT]["status"] == "MEASURED"
    assert rows["a"]["agent_worlds"]["abm_momentum_herd"]["delta_expectancy"] == -0.5
    assert rows["c"]["closure_worlds"][closure_worlds.MARKET_CLOSURE]["why"].startswith("no ")
    # an older synthetic report without the new worlds is UNMEASURED by name, never clean
    doc["scenarios"] = [{"name": "spread_x5"}]
    old = ts.organ_worlds()
    assert old["closure_worlds"]["in_synthetic_regimes"] == []
    assert old["agent_worlds"]["by_world"]["abm_value_anchor"] == {"UNMEASURED": 3}
    assert old["metric"]["closure_world_measured_share"] == 0
