"""THE SYNTHETIC MARKET LABORATORY and SELF-GENERATED BENCHMARKS -- calibrate the instrument.

THE QUESTION THIS DESK CANNOT CURRENTLY ANSWER, and it is the most expensive open question it
has. 420 candidates were tested and 420 died. Two explanations fit that observation exactly as
well: the candidates were worthless, or the gauntlet cannot detect an edge it is handed. The desk
has no way to tell -- and the two demand opposite responses. One says generate better; the other
says the measuring instrument is broken and every future campaign will also return zero.

A SYNTHETIC MARKET SETTLES IT. Generate a price path with a KNOWN edge planted in it at a known
strength, run the desk's own screen over it, and ask whether the screen found it. That is the
gauntlet's POWER. Then run the same screen over paths with NO edge and count how often it says
yes -- the false-positive rate. Neither number is knowable from live data, where the truth is
never available, and both are knowable here for the cost of a random number generator.

  SYNTHETIC MARKET LAB -- LIVE, needs nothing. Paths, planted edges, and a harness that reports
  power and false-positive rate for any screen the desk owns.

  SELF-GENERATED BENCHMARKS -- LIVE. The lab can emit tasks of CALIBRATED difficulty (edge
  strength as the dial), so the desk measures its own detection floor: the weakest edge it can
  reliably find. That floor is the honest answer to "what would we have missed?", and it moves as
  the desk improves, which makes it a progress metric that cannot be gamed by generating more.

WHAT THIS IS NOT. Synthetic data never validates a strategy -- a path is generated by a model of
markets, so anything discovered ON it is a fact about the generator. Its only legitimate use is
measuring an INSTRUMENT against a known truth, which is why every function here returns a
property of the screen and none returns a candidate.

Pure, numpy only, deterministic under a seed.
"""

from __future__ import annotations

from collections.abc import Callable, Sequence
from dataclasses import dataclass

import numpy as np

__all__ = [
    "BENCHMARK_STRENGTHS",
    "LabResult",
    "detection_floor",
    "measure_screen",
    "no_edge_path",
    "planted_edge_path",
]

#: Edge strengths (per-step signal-to-noise) used to sweep difficulty. Spans two orders of
#: magnitude on purpose: the top end proves the harness itself works (a screen that misses a
#: blatant edge has a bug, not a sensitivity limit), and the bottom end is where real crypto
#: edges actually live.
BENCHMARK_STRENGTHS: tuple[float, ...] = (0.30, 0.15, 0.08, 0.04, 0.02, 0.01)


def no_edge_path(n: int, *, seed: int = 0, vol: float = 0.01) -> tuple[np.ndarray, np.ndarray]:
    """(signal, forward_return) with NO relationship between them. The null world.

    The signal is not constant and the returns are not zero -- both are realistic and unrelated.
    A degenerate null (flat signal) would be trivially rejected by any screen and would flatter
    the false-positive measurement into meaninglessness.
    """
    rng = np.random.default_rng(seed)
    return rng.standard_normal(n), rng.standard_normal(n) * vol


def planted_edge_path(n: int, *, strength: float, seed: int = 0,
                      vol: float = 0.01) -> tuple[np.ndarray, np.ndarray]:
    """(signal, forward_return) where the signal genuinely predicts the return.

    `strength` is the fraction of return variance the signal explains, so it maps directly onto
    an information coefficient: a screen that finds strength=0.02 is finding an IC around 0.14,
    which is roughly where a real, tradeable crypto edge sits. This is why the parameter is
    stated in return-variance terms rather than as an abstract "difficulty" dial -- an
    uninterpretable dial produces an uninterpretable detection floor.
    """
    rng = np.random.default_rng(seed)
    sig = rng.standard_normal(n)
    noise = rng.standard_normal(n)
    s = max(0.0, min(1.0, float(strength)))
    fwd = (np.sqrt(s) * sig + np.sqrt(1.0 - s) * noise) * vol
    return sig, fwd


@dataclass(frozen=True)
class LabResult:
    """What a screen actually does, measured against a known truth."""

    strength: float
    trials: int
    power: float                # P(detect | an edge really is there)
    false_positive_rate: float  # P(detect | nothing is there)

    @property
    def usable(self) -> bool:
        """A screen is usable at a strength when it beats coin-flipping on BOTH counts.

        Power alone is not enough and is the trap: a screen that says yes to everything has
        power 1.0 and is worthless. The pair is what matters, which is why they are never
        reported apart.
        """
        return self.power > 0.5 and self.false_positive_rate < 0.5


def measure_screen(screen: Callable[[np.ndarray, np.ndarray], bool],
                   *, strength: float, trials: int = 100, n: int = 500,
                   seed: int = 0) -> LabResult:
    """Run `screen` over `trials` planted worlds and `trials` null worlds.

    BOTH ARE RUN EVERY TIME. Measuring power without the false-positive rate is how a desk
    convinces itself a permissive screen is a sensitive one -- and permissive screens are
    strictly worse than strict ones here, because every false positive consumes a gauntlet slot
    and corrupts the prior for the next candidate.

    Each trial gets its own seed so the two arms are independent and the result is reproducible.
    """
    hits = sum(1 for i in range(trials)
               if screen(*planted_edge_path(n, strength=strength, seed=seed * 100_003 + i)))
    fps = sum(1 for i in range(trials)
              if screen(*no_edge_path(n, seed=seed * 100_003 + 50_000 + i)))
    return LabResult(strength=float(strength), trials=int(trials),
                     power=round(hits / max(1, trials), 4),
                     false_positive_rate=round(fps / max(1, trials), 4))


def detection_floor(screen: Callable[[np.ndarray, np.ndarray], bool],
                    *, strengths: Sequence[float] = BENCHMARK_STRENGTHS,
                    trials: int = 60, n: int = 500, seed: int = 0) -> dict:
    """The weakest edge this screen reliably finds -- the desk's self-generated benchmark.

    THIS IS THE PROGRESS METRIC THAT CANNOT BE GAMED. Hypothesis count rises by generating more;
    survivor count rises by lowering the bar. The detection floor falls only when the desk gets
    genuinely better at finding weak edges, and it is measured against a truth the desk planted
    rather than against its own opinion.

    It is also the honest answer to "what would we have missed?". A floor at 0.08 means every
    edge weaker than that was invisible to this campaign -- so 420 rejections say nothing at all
    about edges below the floor, and reporting them as "tested" would be false.
    """
    rows = [measure_screen(screen, strength=s, trials=trials, n=n, seed=seed) for s in strengths]
    usable = [r for r in rows if r.usable]
    floor = min((r.strength for r in usable), default=None)
    return {
        "sweep": [{"strength": r.strength, "power": r.power,
                   "false_positive_rate": r.false_positive_rate, "usable": r.usable}
                  for r in rows],
        "detection_floor": floor,
        "note": (f"weakest reliably-detected edge: strength {floor}. Anything below it was "
                 "INVISIBLE to this screen, so rejections there are not evidence of absence."
                 if floor is not None else
                 "THE SCREEN DETECTED NOTHING AT ANY STRENGTH TESTED, including the blatant one. "
                 "That is a defect in the instrument, not a statement about the market -- and it "
                 "means a campaign of rejections carries no information whatsoever."),
        "blatant_check": (
            "" if rows and rows[0].usable else
            "FAILS ON THE EASIEST CASE. A screen that cannot find the strongest planted edge has "
            "a bug; fix it before reading anything into the weaker rows."),
    }
