"""AGENT-BASED WORLDS (Tier S layer 16): a market made of traders, not a transform of the tape.

Every other synthetic world bends the history the desk already has. These GENERATE a path from a
small population of agents, so a sleeve can be asked the ecological question history cannot
answer: which kind of market does this edge need? A trend rule that only works when trend
followers dominate, a fade that only works when value traders anchor the price, a breakout that
dies when the liquidity providers step back -- each shows up as a named world it fails in.

THE MARKET, one bar at a time (log price p, the instrument's own per-bar volatility sigma):

    momentum agents   demand  m * tanh((p[t-1] - p[t-1-L]) / (sigma sqrt L))        chase the trend
    value agents      demand  v * tanh((a[t-1] - p[t-1]) / (2 sigma sqrt L))        pull to value
    noise traders     demand  eps_t ~ N(0, 1)                                         random flow
    liquidity agents  absorb the net demand with depth `liq`:  r_t = sigma (D_m + D_v + eps) / liq

`a` is the fundamental the value agents see: the instrument's OWN log price smoothed over 200 bars,
so a world is anchored to the instrument's level and its long drift and nothing else. L is 24
bars. The path is rebuilt onto the sleeve's own bar shapes (every bar repriced by one positive
factor), so session structure, spreads and volumes are the tape's.

THE THREE ECOLOGIES

    abm_momentum_herd         trend followers dominate (m 0.6, v 0.1): persistent, bubbly paths
    abm_value_anchor          value traders dominate (m 0.1, v 0.6): mean-reverting paths
    abm_liquidity_withdrawal  both present (m 0.3, v 0.3) and the liquidity agents at 40% depth:
                              every order moves the price 2.5x as far, spreads x3

Seeded per (seed, world, sleeve), so the same ecology is drawn on any box. ONLY A FAILURE IS A
FINDING: a sleeve that earns more in an invented market has learned nothing, and nothing here is a
score, a rank or a merit.
"""
from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np

LOOKBACK = 24
ANCHOR_BARS = 200


@dataclass(frozen=True)
class Ecology:
    name: str
    momentum: float
    value: float
    liquidity: float
    cost_mult: float = 1.0

    def what(self) -> str:
        return (f"agent-based market: momentum {self.momentum:g}, value {self.value:g}, noise "
                f"1, liquidity depth {self.liquidity:g} (impact x{1 / self.liquidity:.2g})"
                + (f", round trip x{self.cost_mult:g}" if self.cost_mult != 1.0 else ""))


ECOLOGIES: tuple[Ecology, ...] = (
    Ecology("abm_momentum_herd", momentum=0.6, value=0.1, liquidity=1.0),
    Ecology("abm_value_anchor", momentum=0.1, value=0.6, liquidity=1.0),
    Ecology("abm_liquidity_withdrawal", momentum=0.3, value=0.3, liquidity=0.4, cost_mult=3.0),
)
NAMES: tuple[str, ...] = tuple(e.name for e in ECOLOGIES)
BY_NAME: dict[str, Ecology] = {e.name: e for e in ECOLOGIES}


def anchor(logp: np.ndarray, window: int = ANCHOR_BARS) -> np.ndarray:
    """The value agents' fundamental: a trailing mean of the instrument's own log price."""
    c = np.cumsum(np.insert(np.asarray(logp, dtype="float64"), 0, 0.0))
    t = np.arange(len(logp))
    lo = np.maximum(0, t + 1 - window)
    out: np.ndarray = (c[t + 1] - c[lo]) / (t + 1 - lo)
    return out


def simulate(eco: Ecology, n: int, sigma: float, fundamental: np.ndarray, p0: float,
             rng: np.random.Generator) -> np.ndarray:
    """Log returns of an n-bar path generated by the ecology's agents (r[0] = 0)."""
    if n < 2 or not (sigma > 0):
        return np.zeros(max(n, 0), dtype="float64")
    lp = np.empty(n, dtype="float64")
    lp[0] = p0
    r = np.zeros(n, dtype="float64")
    eps = rng.standard_normal(n)
    scale_m = sigma * math.sqrt(LOOKBACK)
    for t in range(1, n):
        back = lp[t - 1 - LOOKBACK] if t - 1 - LOOKBACK >= 0 else lp[0]
        d_m = eco.momentum * math.tanh((lp[t - 1] - back) / scale_m)
        d_v = eco.value * math.tanh((fundamental[t - 1] - lp[t - 1]) / (2.0 * scale_m))
        r[t] = sigma * (d_m + d_v + eps[t]) / eco.liquidity
        lp[t] = lp[t - 1] + r[t]
    return r


def agent_returns(eco: Ecology, close: np.ndarray, rng: np.random.Generator
                  ) -> tuple[np.ndarray, str]:
    """The ecology's returns for a tape with these closes, or (zeros, why) when it cannot run."""
    c = np.asarray(close, dtype="float64")
    if len(c) < ANCHOR_BARS + LOOKBACK + 10:
        return np.zeros(len(c)), f"{len(c)} bars < {ANCHOR_BARS + LOOKBACK + 10}"
    logp = np.log(np.maximum(c, 1e-12))
    diffs = np.diff(logp)
    diffs = diffs[np.isfinite(diffs)]
    sigma = float(np.std(diffs)) if diffs.size > 2 else 0.0
    if sigma <= 0:
        return np.zeros(len(c)), "no dispersion to calibrate the agents on"
    return simulate(eco, len(c), sigma, anchor(logp), float(logp[0]), rng), ""


def autocorr(r: np.ndarray, lag: int = LOOKBACK) -> float:
    """Autocorrelation of `lag`-bar returns: positive in a herd, negative at a value anchor."""
    lp = np.cumsum(np.asarray(r, dtype="float64"))
    k = lp[lag:] - lp[:-lag]
    k = k[::lag]
    if len(k) < 5 or float(np.std(k)) == 0.0:
        return 0.0
    return float(np.corrcoef(k[:-1], k[1:])[0, 1])
