"""Concatenate the complete TRADING CORE into one readable file -> web/algo_full.txt.

The platform is ~300 modules; this bundles the actual algorithm end-to-end (data -> alpha sleeves
-> portfolio construction -> edge-gated leverage -> execution) into a single annotated file you can
read, share, or download from the dashboard URL. Not every helper -- the strategy itself.

    python scripts/bundle_algo.py
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

# the core pipeline, in execution order
_FILES = [
    ("DATA  -- free Binance perp data (OHLCV + funding + basis + taker flow)",
     "libs/data/crypto_source.py"),
    ("ALPHA -- cross-sectional funding carry (the survivor) + ADV-tiered cost",
     "libs/research/crypto_xsec.py"),
    ("ALPHA -- decorrelated sleeves (basis / taker-flow / momentum) + live weights",
     "libs/research/crypto_sleeves.py"),
    ("ALPHA -- delta-neutral cash-and-carry (spot + perp)", "libs/research/cashcarry.py"),
    ("PORTFOLIO -- combine sleeves into one net target weight per perp",
     "scripts/run_crypto_target.py"),
    ("RISK  -- edge-gated leverage (half-Kelly of forward-validated Sharpe)",
     "libs/risk/edge_gate.py"),
    ("EXEC  -- Binance futures testnet connector (orders, positions, P&L)",
     "libs/execution/binance_testnet.py"),
    ("EXEC  -- maker-first execution (post-only, taker fallback)", "libs/execution/maker.py"),
    ("EXEC  -- the live executor loop (rebalance, throttle, gating, snapshot)",
     "scripts/run_crypto_testnet.py"),
]
_OUT = Path("web/algo_full.txt")


def main() -> None:
    root = Path(__file__).resolve().parent.parent
    parts = [f"QUANT TRADING CORE -- consolidated {datetime.now(tz=UTC).isoformat()}",
             "Generated by bundle_algo.py. Full repo lives at C:/Users/dell/quant-platform.",
             "Order = execution pipeline: data -> alpha -> portfolio -> risk -> execution.", ""]
    n = 0
    for label, rel in _FILES:
        p = root / rel
        if not p.exists():
            continue
        body = p.read_text("utf-8")
        n += body.count("\n")
        parts += ["=" * 100, f"# {label}", f"# FILE: {rel}", "=" * 100, "", body, ""]
    _OUT.write_text("\n".join(parts), "utf-8")
    print(f"bundled {len(_FILES)} core files (~{n} lines) -> {_OUT}")


if __name__ == "__main__":
    main()
