#!/usr/bin/env python3
"""THE GLOBAL COVERAGE TENSOR FENCE -- one ladder, generated cells, proven-path coverage, wired.

    python scripts/check_global_coverage_tensor.py                   # portable half
    python scripts/check_global_coverage_tensor.py --require-state   # the box half

PORTABLE HALF (any checkout):
  * ONE LADDER: every state of the world ladder maps to a principal stage, so the principal's
    UNEXPLORED..LIVE ladder is a VIEW of the ladder the tensors share, never a parallel one;
  * the fourteen axes and the 24 source classes are what the principal specified;
  * CELLS ARE GENERATED BY MECHANISTIC COMPATIBILITY: the distinct set is far below the literal
    Cartesian product (a generator that drifted to the product is a lie about coverage);
  * WIRED (III.16): the leg is scheduled in hourly_cycle with a budget, has a layer, and the
    backpressure leg runs on its own clock (CRO 2026-09-30, gap 2);
  * when the artifacts exist: the keys the CRO cycle (#154) reads by exact name are present, and
    the mission set is never empty while holes exist (a throttle reorders, it never cuts to 0).

BOX HALF (--require-state): GLOBAL_COVERAGE_TENSOR.json, SOURCE_ROI.json and
GAUNTLET_BACKPRESSURE.json are present and fresh -- the D-lines read the last one. An absent
artifact on a clean checkout is UNMEASURED and passes the portable half (L1.28a).

This fence caps nothing: it reads, compares and reports.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DESK = ROOT / "desks" / "mt5"
for _p in (str(ROOT), str(DESK), str(DESK / "research")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

REPORT = DESK / "reports" / "GLOBAL_COVERAGE_TENSOR.json"
ROI = DESK / "reports" / "SOURCE_ROI.json"
BACKPRESSURE = DESK / "reports" / "GAUNTLET_BACKPRESSURE.json"
HOURLY = DESK / "research" / "hourly_cycle.py"
#: Two missed hourly passes is a schedule problem, and it is named as one.
STALE_H = 3.0
CRO_KEYS = ("nominal", "distinct", "effective_independent", "proven_path_covered_share",
            "top_missions")
ROI_KEYS = ("funnel", "info_gain_per_compute_hour", "incremental_keff")


def _read(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def _age_h(doc: Any, now: datetime) -> float | None:
    try:
        at = datetime.fromisoformat(str(doc.get("at") or doc.get("generated_at")))
    except (AttributeError, TypeError, ValueError):
        return None
    if at.tzinfo is None:
        at = at.replace(tzinfo=UTC)
    return (now - at).total_seconds() / 3600.0


def portable() -> list[str]:
    import global_coverage_tensor as G

    from libs.research import coverage as CV
    from libs.research.layers import LEG_LAYER

    bad: list[str] = []
    missing = [s for s in CV.WORLD_LADDER_SPEC.states if s not in CV.PRINCIPAL_OF_WORLD]
    if missing:
        bad.append(f"world states with no principal stage (a parallel ladder): {missing}")
    if len(CV.GLOBAL_AXES) != 14:
        bad.append(f"the global tensor has {len(CV.GLOBAL_AXES)} axes, the principal named 14")
    if len(CV.SOURCE_CLASSES) != 24 or len(set(CV.SOURCE_CLASSES)) != 24:
        bad.append(f"{len(CV.SOURCE_CLASSES)} source classes, the principal named 24")
    actors = G.mechanism_actor()
    gen, _meta = G.generate(actors)
    nominal = CV.nominal_cells(G.vocabulary(actors))
    if not gen or len(gen) * 1_000 >= nominal:
        bad.append(f"generated {len(gen)} of a {nominal}-cell product: not a compatibility set")
    src = HOURLY.read_text(encoding="utf-8")
    for needle, why in (('"research/global_coverage_tensor.py"', "the leg is not scheduled"),
                        ('"global_coverage_tensor": 660', "the leg has no LEG_BUDGET_SEC"),
                        ('"gauntlet_backpressure": 600', "backpressure has no leg budget")):
        if needle not in src:
            bad.append(f"hourly_cycle.py: {why} ({needle} absent)")
    if LEG_LAYER.get("global_coverage_tensor") is None:
        bad.append("libs/research/layers.py: global_coverage_tensor belongs to no layer")
    doc = _read(REPORT)
    if isinstance(doc, dict):
        gone = [k for k in CRO_KEYS if k not in doc]
        if gone:
            bad.append(f"{REPORT.name} lacks the CRO cycle's keys {gone}")
        m = doc.get("missions") or {}
        if int(m.get("n_moves") or 0) > 0 and not doc.get("top_missions"):
            bad.append(f"{REPORT.name}: {m.get('n_moves')} holes and ZERO missions emitted")
    roi = _read(ROI)
    if isinstance(roi, dict):
        gone = [k for k in ROI_KEYS if k not in roi]
        if gone:
            bad.append(f"{ROI.name} lacks the CRO cycle's keys {gone}")
    return bad


def state(now: datetime) -> list[str]:
    bad: list[str] = []
    for path in (REPORT, ROI, BACKPRESSURE):
        doc = _read(path)
        if not isinstance(doc, dict):
            bad.append(f"{path.name} absent or unreadable: a scheduled organ produced nothing")
            continue
        age = _age_h(doc, now)
        if age is None or age > STALE_H:
            bad.append(f"{path.name} is {age if age is None else round(age, 1)}h old "
                       f"(> {STALE_H}h): its leg stopped")
    return bad


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--require-state", action="store_true",
                    help="the box half: the artifacts must be present and fresh")
    a = ap.parse_args(argv)
    bad = state(datetime.now(tz=UTC)) if a.require_state else portable()
    if bad:
        for b in bad:
            print(f"FAIL global coverage tensor: {b}")
        return 1
    half = "state" if a.require_state else "portable"
    status = "PRESENT" if REPORT.exists() else "UNMEASURED (no artifact on this tree)"
    print(f"OK global coverage tensor ({half}); artifact {status}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
