#!/usr/bin/env python3
"""DISCOVERY -> LIVE, AS SHORT AS THE EVIDENCE ALLOWS -- the bridge that did not exist.

PRINCIPAL DIRECTIVE (2026-08-07): *alpha discovery to live should not be so long; go live as soon
as possible with little capital, keep and increase what is profitable, retire what is not, allocate
dynamically.* Right, and the desk had no route at all: `libs/research/live_ladder.py` was written
with the arithmetic and had ZERO consumers -- the same defect as the generator that emitted 898,560
candidates with nothing able to run one. A ladder nobody calls is a document.

THE RUNGS, and the only one that is free::

    STAGE-A SURVIVOR -> SHADOW        record only, no capital, starts accruing evidence TODAY
                     -> MIN_LIVE      smallest clip that is still informative
                     -> SCALE         quarter-Kelly on the posterior, capped
                     -> RETIRE        posterior negative beyond the small-size drag

**SHADOW IS THE RUNG THAT SHORTENS THE PIPELINE, AND IT COSTS NOTHING.** The slow part of
discovery -> live was never the paperwork; it was waiting for a backtest to become convincing,
which is not something waiting produces. A shadow record starts the forward clock immediately at
zero capital and zero risk, so by the time capital is available the strategy already has the only
evidence that was ever going to settle it.

**AND THE FLOOR THAT IS NOT OBVIOUS: BELOW A CERTAIN CLIP, GOING LIVE MEASURES YOUR FEES.** Minimum
notionals, tick rounding and the crossed spread do not scale down, so at a small enough size the
cost drag exceeds any plausible edge and the live record cannot distinguish the strategy from its
own costs. Going live tiny then feels like progress while producing an uninformative measurement --
and the natural reading of that measurement is "retire it". So this script computes the smallest
INFORMATIVE clip and recommends SHADOW below it, rather than a live allocation that would generate
data nobody should act on.

PLACES NOTHING. Reads artifacts, prints recommendations, writes a report. Arming live trading is
the principal's act; the Tier-3 dead-man rail is never touched.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from libs.research.live_ladder import (  # noqa: E402
    LiveRecord,
    decide,
    render,
    size_cost_penalty,
)

RECORDS = ROOT / "data" / "live_records.json"
SWEEP = ROOT / "data" / "full_sweep.json"
OUT = ROOT / "data" / "live_ladder.json"

#: A clip is INFORMATIVE when the small-size drag is at most this fraction of the edge the desk
#: would need to care about at all. Above it the live record is mostly a measurement of fees.
DRAG_BUDGET: float = 0.25

#: The smallest edge worth measuring, in bp per round trip. Not a promotion bar -- a RESOLUTION
#: floor: an edge below this is inside the noise of the desk's own cost model, so a live test
#: cannot see it whatever the size.
MIN_INTERESTING_BPS: float = 1.0


def min_informative_clip(*, drag_budget: float = DRAG_BUDGET,
                         edge_bps: float = MIN_INTERESTING_BPS) -> float:
    """Smallest clip at which a live record measures the STRATEGY rather than its costs.

    Solves `size_cost_penalty(clip) <= drag_budget * edge_bps` for clip. Below this the honest
    recommendation is SHADOW: a live test there produces a number whose natural reading is "retire
    it", generated by fees rather than by the strategy.
    """
    target = max(1e-9, drag_budget * edge_bps)
    clip = 1.0
    for _ in range(64):                       # geometric search; the penalty is monotone in clip
        if size_cost_penalty(clip) <= target:
            return clip
        clip *= 1.5
    return clip


def _load(path: Path) -> object | None:
    try:
        return json.loads(path.read_text("utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def records_from(raw: object) -> list[LiveRecord]:
    """Parse forward records. A malformed row is SKIPPED, never defaulted into existence."""
    rows = raw.get("records", []) if isinstance(raw, dict) else (
        raw if isinstance(raw, list) else [])
    out: list[LiveRecord] = []
    for r in rows:
        try:
            out.append(LiveRecord(
                name=str(r["name"]), n_trades=int(r["n_trades"]),
                mean_bps=float(r["mean_bps"]), sd_bps=float(r["sd_bps"]),
                days_live=float(r.get("days_live", 0.0)),
                clip_notional=float(r.get("clip_notional", 0.0))))
        except (KeyError, TypeError, ValueError):
            continue
    return out


def survivors_from(raw: object) -> list[str]:
    """Stage-A survivor keys from a full-sweep report. Absent report -> no survivors, not zero."""
    if not isinstance(raw, dict):
        return []
    return ["|".join(str(x) for x in s.get("key", []))
            for s in raw.get("survivors", []) if isinstance(s, dict)]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--records", type=Path, default=RECORDS)
    ap.add_argument("--sweep", type=Path, default=SWEEP)
    ap.add_argument("--out", type=Path, default=OUT)
    a = ap.parse_args()

    live = records_from(_load(a.records))
    survivors = survivors_from(_load(a.sweep))
    floor = min_informative_clip()

    named = {r.name for r in live}
    # A SURVIVOR WITH NO FORWARD RECORD IS THE WHOLE POINT OF THIS SCRIPT. It should be accruing
    # evidence today at zero capital, not waiting for a queue -- shadow is free and the clock is
    # the only thing that cannot be bought later.
    to_shadow = [s for s in survivors if s not in named]

    verdicts = [decide(r) for r in live]

    rep: dict[str, object] = {
        "ts": datetime.now(tz=UTC).isoformat(),
        "min_informative_clip": round(floor, 2),
        "min_informative_note": (
            f"below a ~{floor:.0f} clip the small-size cost drag exceeds {DRAG_BUDGET:.0%} of a "
            f"{MIN_INTERESTING_BPS:g}bp edge, so a live record there mostly measures fees. SHADOW "
            "is the honest rung under that size -- going live tiny produces a number whose natural "
            "reading is 'retire it', generated by costs rather than by the strategy."),
        "live_records": len(live),
        "stage_a_survivors": len(survivors),
        "to_shadow": to_shadow[:100],
        "verdicts": [
            {"name": v.name, "decision": v.decision, "allocation": round(v.allocation, 4),
             "post_mean_bps": round(v.post_mean_bps, 4), "t": round(v.t_stat, 3),
             "power": v.power_note, "notes": list(v.notes),
             "clip_below_informative_floor": bool(0 < r.clip_notional < floor)}
            for v, r in zip(verdicts, live, strict=True)],
        "authority": ("NONE. Recommendations only -- this script places no orders, sizes no live "
                      "position and does not arm anything. Arming live trading is the principal's "
                      "act and the Tier-3 dead-man rail is untouched."),
    }

    if not live and not survivors:
        rep["verdict"] = "BLOCKED -- NOTHING TO LADDER"
        rep["reason"] = (
            f"no forward records at {a.records.name} and no Stage-A survivors at {a.sweep.name}. "
            "Both are gitignored and live on the collecting box; the sweep has not run (GAP #91) "
            "and nothing has traded (Gate-0 0/17). This is UNMEASURED, not an empty ladder.")
    else:
        rep["verdict"] = (f"{len(to_shadow)} survivor(s) owed a shadow start; "
                          f"{len(live)} record(s) laddered")

    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text(json.dumps(rep, indent=1), "utf-8")

    print(f"live-ladder: {rep['verdict']}")
    print(f"  minimum informative clip ~{floor:.0f} quote units; below it SHADOW is the honest rung")
    for s in to_shadow[:10]:
        print(f"  SHADOW START (free, today): {s}")
    for v in verdicts:
        print("  " + render(v).replace("\n", "\n  "))
    print(f"  artifact: {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
