#!/usr/bin/env python3
"""DISCOVERY -> LIVE, AS SHORT AS THE EVIDENCE ALLOWS -- the bridge that did not exist.

PRINCIPAL DIRECTIVE (2026-08-07): *alpha discovery to live should not be so long; go live as soon
as possible with little capital, keep and increase what is profitable, retire what is not, allocate
dynamically.* Right, and the desk had no route at all: `libs/research/live_ladder.py` was written
with the arithmetic and had ZERO consumers -- the same defect as the generator that emitted 898,560
candidates with nothing able to run one. A ladder nobody calls is a document.

THE RUNGS, and the only one that is free::

    STAGE-A SURVIVOR -> SHADOW        record only, no capital, starts accruing evidence TODAY
                     -> MIN_LIVE      smallest clip that is still informative
                     -> SCALE         quarter-Kelly on the posterior, capped
                     -> RETIRE        posterior negative beyond the small-size drag

**SHADOW IS THE RUNG THAT SHORTENS THE PIPELINE, AND IT COSTS NOTHING.** The slow part of
discovery -> live was never the paperwork; it was waiting for a backtest to become convincing,
which is not something waiting produces. A shadow record starts the forward clock immediately at
zero capital and zero risk, so by the time capital is available the strategy already has the only
evidence that was ever going to settle it.

**AND THE FLOOR THAT IS NOT OBVIOUS: BELOW A CERTAIN CLIP, GOING LIVE MEASURES YOUR FEES.** Minimum
notionals, tick rounding and the crossed spread do not scale down, so at a small enough size the
cost drag exceeds any plausible edge and the live record cannot distinguish the strategy from its
own costs. Going live tiny then feels like progress while producing an uninformative measurement --
and the natural reading of that measurement is "retire it". So this script computes the smallest
INFORMATIVE clip and recommends SHADOW below it, rather than a live allocation that would generate
data nobody should act on.

PLACES NOTHING. Reads artifacts, prints recommendations, writes a report. Arming live trading is
the principal's act; the Tier-3 dead-man rail is never touched.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from libs.portfolio import capital_competition  # noqa: E402
from libs.research import alpha_state, evidence_clock  # noqa: E402
from libs.research.clock_registry import REGISTRY as CLOCK_REGISTRY  # noqa: E402
from libs.research.clock_registry import register_owed  # noqa: E402
from libs.research.live_ladder import (  # noqa: E402
    MIN_OBS_FOR_A_VERDICT,
    LiveRecord,
    decide,
    render,
    size_cost_penalty,
)

RECORDS = ROOT / "data" / "live_records.json"
SWEEP = ROOT / "data" / "full_sweep.json"
OUT = ROOT / "data" / "live_ladder.json"

#: A clip is INFORMATIVE when the small-size drag is at most this fraction of the edge the desk
#: would need to care about at all. Above it the live record is mostly a measurement of fees.
DRAG_BUDGET: float = 0.25

#: The smallest edge worth measuring, in bp per round trip. Not a promotion bar -- a RESOLUTION
#: floor: an edge below this is inside the noise of the desk's own cost model, so a live test
#: cannot see it whatever the size.
MIN_INTERESTING_BPS: float = 1.0


def min_informative_clip(*, drag_budget: float = DRAG_BUDGET,
                         edge_bps: float = MIN_INTERESTING_BPS) -> float:
    """Smallest clip at which a live record measures the STRATEGY rather than its costs.

    Solves `size_cost_penalty(clip) <= drag_budget * edge_bps` for clip. Below this the honest
    recommendation is SHADOW: a live test there produces a number whose natural reading is "retire
    it", generated by fees rather than by the strategy.
    """
    target = max(1e-9, drag_budget * edge_bps)
    clip = 1.0
    for _ in range(64):                       # geometric search; the penalty is monotone in clip
        if size_cost_penalty(clip) <= target:
            return clip
        clip *= 1.5
    return clip


def _load(path: Path) -> object | None:
    try:
        return json.loads(path.read_text("utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def records_from(raw: object) -> list[LiveRecord]:
    """Parse forward records. A malformed row is SKIPPED, never defaulted into existence."""
    rows = raw.get("records", []) if isinstance(raw, dict) else (
        raw if isinstance(raw, list) else [])
    out: list[LiveRecord] = []
    for r in rows:
        try:
            out.append(LiveRecord(
                name=str(r["name"]), n_trades=int(r["n_trades"]),
                mean_bps=float(r["mean_bps"]), sd_bps=float(r["sd_bps"]),
                days_live=float(r.get("days_live", 0.0)),
                clip_notional=float(r.get("clip_notional", 0.0))))
        except (KeyError, TypeError, ValueError):
            continue
    return out


def survivors_from(raw: object) -> list[str]:
    """Stage-A survivor keys from a full-sweep report. Absent report -> no survivors, not zero."""
    if not isinstance(raw, dict):
        return []
    return ["|".join(str(x) for x in s.get("key", []))
            for s in raw.get("survivors", []) if isinstance(s, dict)]


def survivor_t_stats(raw: object) -> dict[str, float]:
    """key -> t. THE EVIDENCE IS IN THE ARTIFACT AND THE CALLER WAS THROWING IT AWAY.

    The first wiring of the governance ladder passed `t_stat=None` for every survivor, so every one
    of them halted at TESTED -> STATISTICALLY_VALID owing a `t_stat` the sweep had already measured
    and written down. A machine that reports missing evidence which is sitting in its own input is
    worse than no machine: it teaches the reader that the ladder's refusals are noise.
    """
    if not isinstance(raw, dict):
        return {}
    out: dict[str, float] = {}
    for s in raw.get("survivors", []):
        if not isinstance(s, dict):
            continue
        try:
            out["|".join(str(x) for x in s.get("key", []))] = float(s["t"])
        except (KeyError, TypeError, ValueError):
            continue
    return out



def state_of(name: str, *, has_forward_record: bool, forward_obs: int,
             t_stat: float | None) -> tuple[alpha_state.AlphaRecord, str]:
    """Place a Stage-A survivor on the governance ladder and say what the NEXT rung costs.

    THE POINT IS THE REFUSAL, NOT THE PLACEMENT. Before `alpha_state` existed, nothing in the code
    made `DISCOVERED -> LIVE` impossible; it was merely undone, and an undone thing looks exactly
    like an impossible one until the morning it does not. This walks each survivor up rung by rung
    with the evidence actually on hand, so the report names the FIRST missing piece of evidence
    rather than an opinion about readiness.

    EVERY SWEEP SURVIVOR STOPS WELL SHORT OF LIVE and that is the correct output, not a bug: a
    screen has zero promotion authority (two-stage discovery law), so the ladder is expected to
    halt at OOS_VALIDATED or below until forward evidence exists.
    """
    rec = alpha_state.AlphaRecord(alpha_id=name)
    # Evidence the sweep artifact genuinely establishes. Nothing is asserted that was not measured:
    # an empty value is treated as missing by the machine, so padding here would be refused anyway.
    ev: dict[str, str] = {
        "expression": name,
        "data_source": "data/bars/*.parquet",
        "n_observations": "sweep-measured",
        "result": "cleared deflated screen F1/F2",
    }
    if t_stat is not None:
        ev |= {"t_stat": f"{t_stat:.3f}", "deflated_hurdle": "5.236",
               "trials_declared": "898560"}
    if has_forward_record:
        ev |= {"shadow_started_at": "recorded", "forward_observations": str(forward_obs)}
    reason = ""
    while True:
        nxt = alpha_state.next_rung(rec.state)
        if nxt is None:
            break
        moved, reason = alpha_state.advance(
            rec, nxt, {k: v for k, v in ev.items()
                       if k in alpha_state.requirements(nxt)})
        if moved.state == rec.state:
            break
        rec = moved
    return rec, reason



def evidence_of(rec: LiveRecord) -> tuple[float, str]:
    """(effective observations, verdict) for a forward record. THE CLOCK, NOT THE CALENDAR.

    A record's `n_trades` is the RAW count and it is the number that flatters: fills clustered in
    one impulse are one observation of one event. The deflated count is what the ladder should
    reason about, and reporting both makes the deflation visible rather than a silent haircut.

    Autocorrelation and event structure are NOT recorded on a LiveRecord today, so they come
    through as unmeasured -- which the clock treats as concentrated rather than independent. That
    is the conservative direction and it is stated in the output rather than hidden.
    """
    st = evidence_clock.EvidenceState(
        raw_observations=rec.n_trades,
        distinct_regimes=0,   # unmeasured -> penalised as single-regime, deliberately
        distinct_symbols=1,
        measured=rec.n_trades > 0)
    eff = evidence_clock.effective_n(st)
    _v, why = evidence_clock.sufficiency(st, required=float(MIN_OBS_FOR_A_VERDICT))
    return eff, why


def competing_allocation(live: list[LiveRecord], verdicts: list) -> dict[str, object]:
    """What every live record would receive if capital were re-competed RIGHT NOW.

    Age is not an input. A record funded because it has been running for months and a record with
    two days of stronger evidence are scored by the same function, so the report shows what the
    allocator would do rather than what precedent did.

    ADVISORY ONLY -- this script places nothing and sizes nothing. It surfaces the comparison so a
    stale allocation cannot hide behind never being questioned.
    """
    cands = []
    for r in live:
        eff, _why = evidence_of(r)
        cands.append(capital_competition.AlphaCandidate(
            name=r.name, edge_bps=r.mean_bps, vol_bps=max(r.sd_bps, 1e-9),
            effective_n=eff, state="LIVE"))
    if not cands:
        return {"headline": "no live records -- nothing to compete", "weights": {}}
    rep = capital_competition.summarise(cands)
    return {"headline": rep["headline"], "weights": capital_competition.allocate(cands),
            "rows": rep["rows"],
            "authority": "ADVISORY. This script places nothing and sizes nothing."}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--records", type=Path, default=RECORDS)
    ap.add_argument("--sweep", type=Path, default=SWEEP)
    ap.add_argument("--registry", type=Path, default=CLOCK_REGISTRY,
                    help="where owed forward clocks are recorded so Stage-B and the dashboard "
                         "can see them; overridable so tests never write the real one")
    ap.add_argument("--out", type=Path, default=OUT)
    a = ap.parse_args()

    live = records_from(_load(a.records))
    sweep_doc = _load(a.sweep)
    survivors = survivors_from(sweep_doc)
    t_by_key = survivor_t_stats(sweep_doc)
    floor = min_informative_clip()

    named = {r.name for r in live}
    # A SURVIVOR WITH NO FORWARD RECORD IS THE WHOLE POINT OF THIS SCRIPT. It should be accruing
    # evidence today at zero capital, not waiting for a queue -- shadow is free and the clock is
    # the only thing that cannot be bought later.
    to_shadow = [s for s in survivors if s not in named]

    # THE WIRE THAT WAS MISSING, and its absence was silent. This script computes `to_shadow` and
    # then declares `authority: NONE -- recommendations only`, which is correct: it must not start
    # clocks. But run_axis_shadows.py -- the organ that DOES start them -- read a hardcoded _AXES
    # dict and could not see this list. So a Stage-A survivor sat between an organ that noticed it
    # and could not act, and an organ that could act and could not see it. Measured 2026-08-09:
    # "9 survivor(s) owed a shadow start; 0 record(s) laddered", every cycle, for as long as the
    # sweep has been producing survivors.
    #
    # Registering is NOT starting a clock and NOT a promotion. It makes the debt VISIBLE to
    # Stage-B and to the dashboard, which is the whole difference between an owed clock and a
    # forgotten one. Forward time is the single input this desk cannot buy later.
    # REGISTRY PATH IS AN ARGUMENT, NOT A CONSTANT. The tests drive main() with tmp sweep/records/
    # out paths; a hardcoded default here would write their fixture survivors into the REAL
    # data/axis_clock_registry.json on every test run. That is not hypothetical -- the same shape
    # polluted web/axis_shadows.json earlier today and turned a cohort fence red.
    owed_registered, owed_why = register_owed(to_shadow, source="run_live_ladder",
                                              registry=a.registry)

    verdicts = [decide(r) for r in live]
    competition = competing_allocation(live, verdicts)

    # GOVERNANCE, WALKED RATHER THAN ASSERTED. Each survivor is stepped up the ladder with the
    # evidence actually in hand; the report names the first MISSING piece. A survivor halting at
    # OOS_VALIDATED is the two-stage discovery law working, not a defect.
    ladder_states = []
    for s_name in survivors:
        rec, why = state_of(s_name, has_forward_record=s_name in named,
                            forward_obs=next((r.n_trades for r in live if r.name == s_name), 0),
                            t_stat=t_by_key.get(s_name))
        ladder_states.append({"alpha": s_name, "state": rec.state, "blocked_by": why,
                              "owes": list(alpha_state.requirements(
                                  alpha_state.next_rung(rec.state) or "")),
                              "line": alpha_state.render(rec)})

    rep: dict[str, object] = {
        "ts": datetime.now(tz=UTC).isoformat(),
        "min_informative_clip": round(floor, 2),
        "min_informative_note": (
            f"below a ~{floor:.0f} clip the small-size cost drag exceeds {DRAG_BUDGET:.0%} of a "
            f"{MIN_INTERESTING_BPS:g}bp edge, so a live record there mostly measures fees. SHADOW "
            "is the honest rung under that size -- going live tiny produces a number whose natural "
            "reading is 'retire it', generated by costs rather than by the strategy."),
        "live_records": len(live),
        "stage_a_survivors": len(survivors),
        "to_shadow": to_shadow[:100],
        "owed_registered": owed_registered,
        "owed_registration_note": owed_why,
        "governance_ladder": ladder_states[:100],
        "capital_competition": competition,
        "evidence_clock": [
            {"name": r.name, "raw_trades": r.n_trades,
             "effective_observations": round(evidence_of(r)[0], 2),
             "verdict": evidence_of(r)[1]} for r in live[:50]],
        "governance_note": (
            "walked by libs/research/alpha_state: one rung at a time, each rung's\n"
            "evidence required by name. A skipped rung is REFUSED, not merely\n"
            "undone. LIVE additionally requires a principal authorisation token no\n"
            "organ can synthesise -- this script grants nothing."),
        "verdicts": [
            {"name": v.name, "decision": v.decision, "allocation": round(v.allocation, 4),
             "post_mean_bps": round(v.post_mean_bps, 4), "t": round(v.t_stat, 3),
             "power": v.power_note, "notes": list(v.notes),
             "clip_below_informative_floor": bool(0 < r.clip_notional < floor)}
            for v, r in zip(verdicts, live, strict=True)],
        "authority": ("NONE. Recommendations only -- this script places no orders, sizes no live "
                      "position and does not arm anything. Arming live trading is the principal's "
                      "act and the Tier-3 dead-man rail is untouched."),
    }

    if not live and not survivors:
        rep["verdict"] = "BLOCKED -- NOTHING TO LADDER"
        rep["reason"] = (
            f"no forward records at {a.records.name} and no Stage-A survivors at {a.sweep.name}. "
            "Both are gitignored and live on the collecting box; the sweep has not run (GAP #91) "
            "and nothing has traded (Gate-0 0/17). This is UNMEASURED, not an empty ladder.")
    else:
        rep["verdict"] = (f"{len(to_shadow)} survivor(s) owed a shadow start "
                          f"({owed_registered} newly registered for Stage-B); "
                          f"{len(live)} record(s) laddered")

    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text(json.dumps(rep, indent=1), "utf-8")

    print(f"live-ladder: {rep['verdict']}")
    print(f"  minimum informative clip ~{floor:.0f} quote units; below it SHADOW is the honest rung")
    for s in to_shadow[:10]:
        print(f"  SHADOW START (free, today): {s}")
    for v in verdicts:
        print("  " + render(v).replace("\n", "\n  "))
    for st in ladder_states[:5]:
        print("  " + str(st["line"]))
    print(f"  capital competition: {competition['headline']}")
    print(f"  artifact: {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
