#!/usr/bin/env python3
# INTENDED CADENCE (NOT wired here -- ops/crontab.manifest is owned by another agent this wave, so
# this comment is the request, not the installation):
#
#     23 */6 * * *  cd /opt/quant && python3 scripts/screen_orderbook_state.py --files 240
#
# Six-hourly, offset off the hour so it never collides with the recorders' rotation or with
# scripts/screen_moat.py. It is read-only over data/moat and writes exactly one artifact; running
# it more often buys nothing, because the pre-registered family is fixed and the tape only grows in
# calendar time. On a box without data/moat it exits 0 with a NOT-READABLE-HERE artifact, so
# installing the line early is harmless.
"""STAGE-A SCREEN: ORDER-BOOK MICROSTRUCTURE STATE -- pre-registered BEFORE any result is read.

================================================================================================
THIS DOCSTRING IS THE PRE-REGISTRATION. It was written before the screen was run against any tape,
and nothing below it may be edited in response to a result. Charter section 26 clause 3: every
construction tried is logged, not only the one that printed. The desk's graveyard is what happens
without this.
================================================================================================

WHY THIS CLASS, MEASURED, NOT ASSERTED
--------------------------------------
`scripts/run_mechanism_census.py` ranks `orderbook_microstructure_state` #1 of 20 economic classes
(gap score 0.396 = plausibility 0.80 x orthogonality 0.90 x feasibility 0.55 x depth deficit 1.00),
coverage NAMED-UNTESTED: one named construction, ZERO tested candidates. Separately,
`scripts/measure_cross_mechanism_corr.py` measured the desk's 44-candidate maximum-power campaign
occupying 4 of 20 classes (effective classes 2.787, diversity 0.139) and a cross-mechanism
N_eff of 4.08 against the ~100 independent bets a weak-edge portfolio needs for a Sharpe-2 ceiling.
The binding constraint is DISTINCT MECHANISMS, and this is the highest-value distinct one the desk
has never run. It is untested for want of a SCREEN, not for want of data: ~10 GB of L2 depth tape
sits under data/moat, written by run_recorder.py / run_recorder_bybit.py / run_recorder_spot.py.

1. THE ECONOMIC MECHANISM -- WHO PAYS WHOM, AND WHY THE PAYMENT PERSISTS
------------------------------------------------------------------------
TWO PAYERS, and both pay for a physical reason rather than a mistaken belief.

  THE IMPATIENT TAKER pays a spread the book's state had ALREADY widened. His urgency is
  exogenous: a liquidation engine unwinding a maintenance-margin breach, a hedger with a delta to
  flatten before a funding stamp, a retail market order. None of them is choosing to trade at that
  instant because they think it is a good price; they are trading because they must. Urgency that
  comes from a constraint cannot be updated away by learning that this screen exists.

  THE STALE RESTING MAKER pays by being picked off. A quote that does not withdraw inside the
  venue's matching latency is adversely selected on every information event. That is a
  TECHNOLOGICAL cost -- the speed of light and the exchange's queue -- not a mispricing, so it does
  not compete away; it accrues to whoever is faster, and the residue accrues to whoever can SEE the
  withdrawal happening.

  WHY THE PAYMENT PERSISTS. (a) Latency is strictly positive and bounded below by physics.
  (b) Forced flow is generated by constraints (margin, mandate, funding clock), not by opinion.
  (c) The observation itself is not purchasable retroactively: pre-recorder L2 does not exist for
  sale at any price, so the population competing for this rent is bounded by who was RECORDING at
  the time, not by who has capital. That third leg is why the census scores this class 0.90 on
  orthogonality and why the desk's own asymmetry ledger grades the tape EXCLUSIVE.

  WHAT WOULD KILL THE STORY. If the rent is fully captured by co-located market makers inside the
  matching engine's latency, nothing survives at a 60s-900s horizon and the residual IC is zero.
  That is the honest null and this screen is built to be able to report it.

2. THE FALSIFIABLE CLAIM
------------------------
  H0 (the desk's standing prior, and what a null result CONFIRMS):
      For every pre-registered (construction x horizon) cell, the RESIDUALISED book-state signal
      observed at a bar boundary has zero forward information about the next bar's return:
      |IC| < 0.03, and any raw forward IC is fully accounted for by the state's concurrency with
      the return already realised.

  H1 (what would refute H0):
      At least one cell shows |IC| >= 0.03 with best timing Sharpe >= 0.5 on the RESIDUALISED
      form, is POWERED by the harness's own detection floor, passes the angle-20 de-contamination
      gate, and clears the family-wise critical value at alpha = 0.05 over the pre-registered
      family below.

  H0 is refutable and H1 is refutable. A cell that clears H1 earns a FORWARD CLOCK and nothing
  else -- Stage A has zero promotion authority and this script cannot size a position, cannot
  write a clock file, and cannot consume one of the desk's twelve Holm-corrected forward slots.

3. THE EXACT CONSTRUCTIONS -- FIVE, FIXED, NAMED BEFORE ANY RESULT
------------------------------------------------------------------
All five are computed at the bar's right edge from `libs/research/orderbook_state.py`. Each is
screened in BOTH forms (raw and residualised), and both are reported however they land.

    obi_touch             (bid - ask) resting size at the touch, normalised. The one primitive a
                          public feed does publish -- included as the CONTROL: if the exclusive
                          constructions cannot beat it, the tape is not buying anything.
    obi_deep              the same over 20 recorded levels. Not reconstructable without the tape.
    book_slope_asymmetry  log-depth decay away from mid on the bid side MINUS the ask side. Which
                          side is thin BEHIND the quote. `moat_mine.book_slope` pools both sides
                          and therefore averages away exactly this difference.
    spread_state          quoted spread in bps. The harness's own 20-period z-score turns it into
                          a regime rather than a level, which is the form the mechanism predicts.
    withdrawal_asymmetry  bar-to-bar fractional drop in bid-side resting depth MINUS the ask side.
                          The side that withdraws first is the side that believes it is about to
                          be picked off -- the class's own economic definition, made a number.

  FORMS (both always reported, per clause 3):
    raw           the state as observed. Its `same_period_corr` IS the contamination measurement;
                  it is reported precisely so a kill can name its cause.
    residualised  the state orthogonalised against the SAME-BAR return with a beta fitted on
                  strictly prior bars. THE PRIMARY FORM. Only a residualised cell can be a
                  survivor of this screen; a raw cell that scores well while its twin collapses is
                  recorded as CONCURRENT-ONLY, which is a kill, not a find.

  HORIZONS: bars of 60s, 300s, 900s. Chosen to bracket the mechanism's own clock -- resting depth
  is refreshed on a seconds scale and the rent is collected within minutes, so a daily horizon
  would be testing a different claim. Not tuned: these are `screen_moat.py`'s horizons, adopted
  unchanged so this screen cannot be accused of having searched over the horizon grid.

4. THE MULTIPLICITY CHARGE -- alpha STAYS 0.05
----------------------------------------------
  Family = 5 constructions x 2 forms x 3 horizons = 30 pre-registered cells.

  The critical value is `libs.validation.type2_cost.critical_z(alpha=0.05, n_tests=N, two_sided)`
  -- Bonferroni, which the desk's own module documents as its approximation to the Romano-Wolf
  max-null critical value. N is the LARGER of the pre-registered 30 and the number of cells
  actually scored in the run: a run that reads less tape than planned cannot buy significance by
  shrinking its own family, and a run that screens several symbol-cells pays for all of them.
  A cell must satisfy |IC| * sqrt(n_eff) >= z_crit ON TOP of every gate the harness already
  applies. alpha is never moved; the family only ever grows.

5. THE CONTAMINATION HAZARD -- THIS IS THE WHOLE GAME
-----------------------------------------------------
ORDER-BOOK STATE IS CONCURRENT WITH PRICE. The side that just got hit is the thin one, so
imbalance at a bar boundary is mechanically a restatement of the return that bar just produced.
The census's own note on the neighbouring `informed_order_flow` class records that every kill so
far died exactly here: flow is concurrent with price and fails de-contamination. Coinbase-premium,
Turkey-premium and kimchi died the same way.

So the screen does three things and none of them is optional:
  (a) It runs the AUDITED harness `libs/research/axis_screen.stage_a_screen`, whose angle-20
      de-contamination gate is baked in. Nothing here hand-rolls a screen and nothing bypasses the
      gate.
  (b) It screens the RESIDUALISED construction as the PRIMARY: the state is orthogonalised against
      the same-bar return BEFORE it is asked to predict the next bar. The beta is fitted on
      STRICTLY PRIOR bars, so the residual is computable at the decision instant and is not itself
      a leak (a full-sample beta would make the residual depend on returns that had not happened).
  (c) It reports the raw twin's `same_period_corr` next to every residualised result, so a
      collapse from raw to residual is visible as the artifact it is rather than as a missing row.

6. THE ALIGNMENT RULE -- DECLARED, because unstated alignment voids the screen (clause 4)
-----------------------------------------------------------------------------------------
  Bars are fixed, wall-clock-anchored, half-open UTC-ms intervals: bar k = [k*W, (k+1)*W), right
  edge b_k = (k+1)*W.
  SIGNAL   state[k] = the LAST depth snapshot with t strictly < b_k. Decision time b_k.
  TARGET   p[k] = the FIRST trade print with t >= b_k (+ decision_lag_ms, default 0);
           r[k] = p[k]/p[k-1] - 1, the return realised OVER bar k.
  PAIRING  the harness shifts forward itself and pairs state[k] with r[k+1], i.e. the window
           [b_k, b_{k+1}). THE BAR CONTAINING THE SNAPSHOT IS EXCLUDED FROM THE PREDICTED WINDOW.
  GAPS     a period whose edges are not exactly one bar apart is DROPPED, not priced. Masking
           compacts the series, which ATTENUATES an IC toward zero and never leaks; the count of
           dropped periods is reported rather than buried.

  DECLARED LOOK-AHEAD RISK, stated because it cannot be designed away: r[k] closes on the same
  print that opens r[k+1], so decision_lag_ms = 0 assumes a zero-latency fill. It is an UPPER
  BOUND on anything achievable. Any survivor MUST be re-run at the desk's measured round trip
  (`--decision-lag-ms`) before it is believed; that re-run can only ever weaken the reading.

7. NEGATIVE RESULTS ARE THE EXPECTED DELIVERABLE (clause 6)
-----------------------------------------------------------
The desk's prior is 420 price-family hypotheses, 0 survivors. Zero survivors here is a publishable
result -- but ONLY if it is distinguishable from blindness. Every cell therefore carries a
`libs/validation/type2_cost` reading: its effective sample, its detection floor at the family-wise
critical value, and the power it had at the declared effect sizes. A cell labelled UNDERPOWERED is
NOT graveyard-grade and must never be recorded as a refutation; a cell labelled POWERED-NEGATIVE
is permanent knowledge and is emitted with its reason and its floor.

8. DATA, AND THE REFUSAL TO FABRICATE
-------------------------------------
The moat tape is VPS-only and ABSENT from a fresh checkout (data/ is gitignored). This script has
NO synthetic fallback and no generator anywhere in its import graph. When the tape is unreadable it
writes a NOT-READABLE-HERE status artifact naming the exact missing paths and exits 0. A survivor
found on generated depth is a fact about the generator, and it would enter the funnel wearing the
same vocabulary as a real one.

Read-only over data/moat. Writes one artifact. No keys, no order paths, zero promotion authority.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.build_bars import trades_from  # noqa: E402

from libs.research.axis_screen import stage_a_screen  # noqa: E402
from libs.research.moat_microstructure import read_partition  # noqa: E402
from libs.research.orderbook_state import (  # noqa: E402
    CONSTRUCTIONS,
    FORMS,
    Alignment,
    bar_close_states,
    boundary_prices,
    contiguous_mask,
    period_returns,
    residualise,
    snapshot_states,
)
from libs.validation.type2_cost import (  # noqa: E402
    DECLARED_CORRELATION_EFFECTS,
    DEFAULT_ALPHA,
    Type2Cost,
    correlation_negative,
    critical_z,
    headline,
    indeterminate,
)

SCHEMA_VERSION = "1.0.0"
MECHANISM_CLASS = "orderbook_microstructure_state"

MOAT = ROOT / "data/moat"
#: The venue roots the three recorders write. Named individually so a NOT-READABLE-HERE artifact
#: tells the reader WHICH recorder is not running, not merely that something is missing.
VENUE_DIRS = ("fut", "spot", "bybit")
RECORDERS = ("scripts/run_recorder.py -> data/moat/fut",
             "scripts/run_recorder_spot.py -> data/moat/spot",
             "scripts/run_recorder_bybit.py -> data/moat/bybit")
REPORT = ROOT / "data/orderbook_state_screen.json"

#: PRE-REGISTERED. Bars in milliseconds. Adopted unchanged from screen_moat.py so this screen
#: cannot be accused of having searched the horizon grid.
HORIZONS_MS = (60_000, 300_000, 900_000)

#: PRE-REGISTERED family size: 5 constructions x 2 forms x 3 horizons. The multiplicity charge is
#: never smaller than this, whatever the run actually manages to score.
PREREGISTERED_FAMILY = len(CONSTRUCTIONS) * len(FORMS) * len(HORIZONS_MS)

#: The harness floors, restated so the artifact records the bar it was judged against. NOT tunable
#: from the command line: a bar that can be moved at the call site is not a bar.
IC_MIN = 0.03
SHARPE_MIN = 0.5

#: Paired (signal, return) observations below which a cell is not screened at all. `axis_screen`
#: needs >30 after its 20-period z-score warmup; 60 is screen_moat.py's floor and is kept so the
#: two organs mean the same thing by "too short".
MIN_PAIRED = 60

FILE_BUDGET = 240

#: Verdicts the harness returns that constitute graveyard-grade negative knowledge, each with the
#: reason it is filed under. Anything UNDERPOWERED is deliberately absent: "could not tell" is not
#: "it is dead", and the graveyard is permanent.
_KILL_REASONS = {
    "SCREEN-WEAK": ("powered and below the floors: |IC| < 0.03 or best timing Sharpe < 0.5 on a "
                    "sample that could have resolved an effect at 0.03"),
    "TIMING-ARTIFACT": ("angle-20 de-contamination FAILED: |same-period corr| > 0.20 or residual "
                        "IC collapsed below half the raw IC -- the coinbase/turkey/kimchi failure "
                        "mode, and the one this class was always most exposed to"),
    "SUSPECT-LOOKAHEAD": ("too strong to be credible at this horizon -- read as misalignment, "
                          "never as edge; NEVER earns a clock"),
}
_KILL_VERDICTS = tuple(_KILL_REASONS)


def _rel(p: Path) -> str:
    try:
        return str(p.relative_to(ROOT))
    except ValueError:
        return str(p)


def pre_registration(alignment: Alignment) -> dict[str, Any]:
    """The machine-readable echo of this module's docstring. Written into EVERY artifact.

    A pre-registration that lives only in prose cannot be diffed, so a later run that quietly
    screened a sixth construction would look identical to this one in the record.
    """
    return {
        "mechanism_class": MECHANISM_CLASS,
        "census_rank": 1,
        "census_gap_score": 0.396,
        "census_coverage": "NAMED-UNTESTED",
        "payer": (
            "the impatient taker who crosses a spread the book's state had already widened (his "
            "urgency is exogenous -- liquidation, hedge, mandate -- not an opinion that can be "
            "updated away), and the stale resting maker who is picked off because he did not "
            "withdraw inside the venue's matching latency (a technological cost bounded below by "
            "physics, not a mispricing)"
        ),
        "persistence": (
            "latency is strictly positive; forced flow is generated by constraints rather than by "
            "belief; and the observation itself cannot be bought retroactively, so the population "
            "competing for the rent is bounded by who was RECORDING, not by who has capital"
        ),
        "falsifier": (
            "H0: every residualised cell has |IC| < 0.03 and any raw forward IC is fully "
            "accounted for by concurrency with the return already realised. H1 needs |IC| >= 0.03, "
            "best timing Sharpe >= 0.5, POWERED, angle-20 gate passed, AND |IC|*sqrt(n_eff) >= the "
            "family-wise critical value at alpha 0.05."
        ),
        "constructions": sorted(CONSTRUCTIONS),
        "forms": list(FORMS),
        "primary_form": "residualised",
        "horizons_ms": list(HORIZONS_MS),
        "family_preregistered": PREREGISTERED_FAMILY,
        "alpha": DEFAULT_ALPHA,
        "multiplicity": (
            "Bonferroni critical_z over N = max(preregistered family, cells scored). Shrinking the "
            "run cannot shrink the charge; alpha never moves."
        ),
        "ic_min": IC_MIN,
        "sharpe_min": SHARPE_MIN,
        # The RULE, shown once with a representative bar width. It is identical at every horizon --
        # only `bar_ms` changes -- and each row carries the exact alignment it was screened under,
        # so a reader never has to infer which width produced a given number.
        "alignment": {**alignment.as_dict(),
                      "applies_at_each_horizon_ms": list(HORIZONS_MS),
                      "bar_ms_shown_is_representative": True},
        "contamination_hazard": (
            "book state is CONCURRENT with price -- the side that just got hit is the thin one -- "
            "so a raw forward IC is very largely a restatement of the bar that just finished. The "
            "residualised form is the primary; the raw twin's same_period_corr is reported next to "
            "it so a collapse is visible as the artifact it is."
        ),
        "authority": "NONE -- Stage A. No promotion, no sizing, no forward-clock file written.",
        "no_synthetic_fallback": (
            "this script has no generator in its import graph: an unreadable tape yields a status "
            "artifact, never a fabricated row"
        ),
    }


def missing_paths() -> list[str]:
    """Exact paths whose absence blocks the screen, in the order a reader should check them."""
    out: list[str] = []
    if not MOAT.is_dir():
        out.append(_rel(MOAT))
    for v in VENUE_DIRS:
        d = MOAT / v
        if not d.is_dir():
            out.append(_rel(d))
        elif not any(d.rglob("*.jsonl.gz")):
            out.append(f"{_rel(d)}/**/*.jsonl.gz (directory exists, no partitions)")
    return out


def not_readable_here(alignment: Alignment) -> dict[str, Any]:
    """THE HONEST EMPTY RESULT. Not a failure, not a zero, and above all not a simulation.

    `mechanism_census.py` already distinguishes NOT-READABLE-HERE from UNTESTED for exactly this
    reason: a runtime-only artifact absent from a checkout must never be counted as evidence of
    absence. The same word is used here so the census can read this artifact without a translation
    layer.
    """
    return {
        "schema_version": SCHEMA_VERSION,
        "generated_utc": datetime.now(tz=UTC).isoformat(),
        "script": "scripts/screen_orderbook_state.py",
        "status": "NOT-READABLE-HERE",
        "stage": "A (zero promotion authority)",
        "mechanism_class": MECHANISM_CLASS,
        "missing_paths": missing_paths(),
        "written_by": list(RECORDERS),
        "why": (
            "the L2 depth tape is VPS-only and data/ is gitignored, so this is EXPECTED in a fresh "
            "checkout and a REAL blocker on the live box. The screen is otherwise complete and "
            "runs unchanged the moment the tape is present."
        ),
        "refusal": (
            "no synthetic tape is generated and no result is reported. A survivor found on "
            "generated depth is a fact about the generator, and it would enter the funnel wearing "
            "the same vocabulary as a real one."
        ),
        "pre_registration": pre_registration(alignment),
        "rows": [],
        "survivors": [],
        "graveyard": [],
        "tally": {},
        "authority": "NONE -- Stage A.",
    }


def tape_files() -> list[Path]:
    """Every recorded partition, venue/symbol/*.jsonl.gz, in a stable order."""
    if not MOAT.is_dir():
        return []
    out: list[Path] = []
    for vdir in sorted(p for p in MOAT.iterdir() if p.is_dir()):
        for sym in sorted(p for p in vdir.iterdir() if p.is_dir()):
            out.extend(sorted(sym.glob("*.jsonl.gz")))
    return out


def cells(files: list[Path]) -> dict[tuple[str, str, str], list[Path]]:
    """(venue, symbol, day) -> partitions. The SAME grid mine_moat.py and screen_moat.py use, so a
    cell that is mined but unscreened by this organ is a visible hole rather than an accounting
    mismatch between two different notions of 'cell'."""
    out: dict[tuple[str, str, str], list[Path]] = defaultdict(list)
    for f in files:
        day = f.stem.split(".")[0].split("_")[0]
        out[(f.parent.parent.name, f.parent.name, day)].append(f)
    return {k: sorted(v) for k, v in sorted(out.items())}


def trade_arrays(rows: list[dict[str, Any]]) -> tuple[np.ndarray, np.ndarray]:
    """(ms, price) for every print, ascending. Parsed by the ONE existing price reader.

    `scripts.build_bars.trades_from` understands both recorder schemas including Bybit's nested
    list and its `v`/`size` quantity split. A second parser here would be a second place for the
    mixed-schema silent-zero bug that already scarred moat_audit.py.
    """
    tr: list[tuple[int, float, float]] = []
    for r in rows:
        tr.extend(trades_from(r))
    if len(tr) < 2:
        return np.zeros(0, dtype="int64"), np.zeros(0)
    tr.sort(key=lambda x: x[0])
    return (np.array([x[0] for x in tr], dtype="int64"),
            np.array([x[1] for x in tr], dtype="float64"))


def screen_cell(label: str, rows: list[dict[str, Any]], *,
                decision_lag_ms: int) -> list[dict[str, Any]]:
    """Every pre-registered (construction x form x horizon) cell for one (venue, symbol, day).

    EVERY cell produces a row, including the ones that could not be screened. A construction that
    silently vanishes from the record is indistinguishable from one that was never tried, and the
    difference is exactly what clause 3 exists to preserve.
    """
    snap_ms, states = snapshot_states(rows)
    t_ms, t_px = trade_arrays(rows)
    out: list[dict[str, Any]] = []
    if snap_ms.size == 0 or t_ms.size == 0:
        return [{"cell": label, "verdict": "NO-INPUT", "snapshots": int(snap_ms.size),
                 "prints": int(t_ms.size),
                 "why": ("this partition carries no readable depth snapshots or no prints -- more "
                         "recording fixes the second, nothing fixes the first for a file already "
                         "written")}]

    for bar_ms in HORIZONS_MS:
        al = Alignment(bar_ms=bar_ms, decision_lag_ms=decision_lag_ms)
        edges, closes = bar_close_states(snap_ms, states, alignment=al)
        contig = contiguous_mask(edges, alignment=al)
        breaks = int((~contig[1:]).sum()) if contig.size > 1 else 0
        # A GAP IS NOT A PERIOD, AND IT IS BLANKED BEFORE THE ORTHOGONALISATION, NOT AFTER. A
        # recorder outage makes one nominal 60-second period span hours; masking it out of the IC
        # alone would still let it into the expanding beta, where a single enormous "same-period
        # return" would drag the fit and contaminate EVERY residual after it. Blanking here means
        # the gap cannot enter either computation.
        ret = np.where(contig, period_returns(
            boundary_prices(t_ms, t_px, edges, alignment=al)), np.nan)

        for cname, fn in sorted(CONSTRUCTIONS.items()):
            raw = np.asarray(fn(closes), dtype="float64")
            forms = {"raw": raw, "residualised": residualise(raw, ret)}
            for form in FORMS:
                sig = forms[form]
                ok = np.isfinite(sig) & np.isfinite(ret)
                name = f"{label}|{cname}|{form}|{bar_ms}ms"
                base: dict[str, Any] = {
                    "cell": label, "construction": cname, "form": form, "bar_ms": bar_ms,
                    "n_paired": int(ok.sum()), "gap_breaks": breaks,
                    "alignment": al.as_dict(),
                }
                if int(ok.sum()) < MIN_PAIRED:
                    out.append({**base, "verdict": "TOO-FEW-PAIRS",
                                "why": (f"{int(ok.sum())} paired observations against a floor of "
                                        f"{MIN_PAIRED} -- an IC here would describe coincidence"),
                                "type2": indeterminate(
                                    name,
                                    "fewer paired observations than the screen's own floor",
                                    source="scripts/screen_orderbook_state.py",
                                    effect_unit="ic").as_dict()})
                    continue
                res = stage_a_screen(sig[ok], ret[ok], name=name,
                                     ic_min=IC_MIN, sharpe_min=SHARPE_MIN,
                                     horizon_days=al.horizon_days)
                out.append({**base, **{k: v for k, v in res.items() if k != "name"}})
    return out


def _significance(rows: list[dict[str, Any]], *, n_family: int) -> None:
    """Attach the family-wise bar to every scored row, in place.

    Bonferroni over N -- the desk's own documented approximation to the Romano-Wolf max-null
    critical value (`libs/validation/type2_cost`). It is applied ON TOP of every gate the harness
    already ran, so it can only ever remove candidates.
    """
    z_crit = critical_z(DEFAULT_ALPHA, n_family, two_sided=True)
    for r in rows:
        n_eff = r.get("n_eff")
        ic = r.get("ic")
        if not isinstance(n_eff, (int, float)) or not isinstance(ic, (int, float)):
            continue
        if not np.isfinite(float(n_eff)) or not np.isfinite(float(ic)) or float(n_eff) <= 0:
            continue
        need = float(z_crit) / float(np.sqrt(float(n_eff)))
        r["family_size"] = int(n_family)
        r["family_z_critical"] = round(float(z_crit), 4)
        r["ic_needed_family_wise"] = round(need, 4)
        r["clears_family_wise"] = bool(abs(float(ic)) >= need)


def _type2(rows: list[dict[str, Any]], *,
           n_family: int) -> list[tuple[dict[str, Any], Type2Cost]]:
    """Attach the Type-II reading to every scored row, in place; return (row, cost) pairs.

    Pairs rather than bare costs because the HEADLINE is a statement about recorded NEGATIVES, and
    the caller cannot know which rows those are until `classify` has run. Labelling a survivor as
    an underpowered negative would be a category error -- its detection floor is still the right
    number to publish per row, but it is not part of "how much do this run's nulls know".

    A zero without a power figure is unfalsifiable: it cannot be told apart from "we could not have
    seen anything even if it were there", and those two statements retire opposite things -- a
    hypothesis class in the first case, an INSTRUMENT in the second.
    """
    costs: list[tuple[dict[str, Any], Type2Cost]] = []
    for r in rows:
        n = r.get("n")
        if not isinstance(n, (int, float)) or float(n) <= 0:
            continue
        cost = correlation_negative(
            f"{r.get('cell')}|{r.get('construction')}|{r.get('form')}|{r.get('bar_ms')}ms",
            n_obs=float(n),
            source="scripts/screen_orderbook_state.py",
            # Bars are NON-OVERLAPPING: one bar is one target, so no overlap deflator applies.
            # This is the same n_eff the harness computed, by construction -- the two must never
            # disagree about whether a cell was powered.
            horizon_periods=1.0,
            panel_width=1,
            n_tests=n_family,
            alpha=DEFAULT_ALPHA,
            effect_unit="ic",
            note=("bars are non-overlapping so n_eff = paired bars; serial correlation in book "
                  "state is NOT deflated here, so this power figure is an upper bound. TWO FLOORS "
                  "ARE REPORTED AND THEY ANSWER DIFFERENT QUESTIONS: the harness's "
                  "min_detectable_ic is the UNADJUSTED (N=1) floor and is what its SCREEN-WEAK / "
                  "SCREEN-UNDERPOWERED split already encodes, while min_detectable_effect here is "
                  "the floor at the FAMILY-WISE charge -- the bar a FIND had to clear. A cell can "
                  "be powered against the first and not the second; that is not a contradiction, "
                  "it is the price of testing 30 cells."),
        )
        r["type2"] = cost.as_dict()
        r["type2_label"] = cost.label
        costs.append((r, cost))
    return costs


def verdict_pairs(rows: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Index scored rows by (cell, construction, form) so a residual can find its raw twin."""
    return {f"{r.get('cell')}|{r.get('construction')}|{r.get('bar_ms')}|{r.get('form')}": r
            for r in rows}


def classify(rows: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """(survivors, graveyard rows). CONSERVATIVE ON BOTH SIDES.

    A SURVIVOR must be the RESIDUALISED form, must have earned SCREEN-INTERESTING from the audited
    harness, must be POWERED by the harness's own detection floor, and must clear the family-wise
    critical value. The raw form is never a survivor of this screen -- it is the contamination
    measurement -- so a state that scores only before orthogonalisation is recorded as a kill.

    A GRAVEYARD ROW is a POWERED negative or an artifact verdict, WITH its reason and its detection
    floor. UNDERPOWERED cells are excluded on purpose: the graveyard is permanent and "could not
    tell" must never be filed as "it is dead".
    """
    idx = verdict_pairs(rows)
    survivors: list[dict[str, Any]] = []
    graveyard: list[dict[str, Any]] = []
    for r in rows:
        verdict = str(r.get("verdict", ""))
        form = str(r.get("form", ""))
        key = f"{r.get('cell')}|{r.get('construction')}|{r.get('bar_ms')}"
        twin = idx.get(f"{key}|raw") if form == "residualised" else idx.get(f"{key}|residualised")
        if form == "residualised" and verdict == "SCREEN-INTERESTING" \
                and bool(r.get("powered")) and bool(r.get("clears_family_wise")):
            survivors.append({
                "cell": r.get("cell"), "construction": r.get("construction"),
                "bar_ms": r.get("bar_ms"), "ic": r.get("ic"), "n": r.get("n"),
                "n_eff": r.get("n_eff"),
                "ic_needed_family_wise": r.get("ic_needed_family_wise"),
                "raw_twin_same_period_corr": (twin or {}).get("same_period_corr"),
                "raw_twin_ic": (twin or {}).get("ic"),
                "earns": ("a pre-registered FORWARD CLOCK and nothing else -- this script does not "
                          "write one; consuming one of twelve Holm-corrected forward slots is a "
                          "principal-visible act"),
            })
            continue
        floor = ((r.get("type2") or {}).get("min_detectable_effect")
                 if isinstance(r.get("type2"), dict) else None)
        # CONCURRENT-ONLY IS CHECKED FIRST, and the ordering is the point. A residualised cell whose
        # raw twin scored would otherwise land on the generic SCREEN-WEAK row, which records THAT
        # it died without recording WHY -- and "why" is the entire finding for this mechanism class:
        # the forecast was a restatement of a bar that had already happened. Clause 6 asks for the
        # reason, not merely the verdict. It still requires `powered`, so an underpowered residual
        # never gets to claim the raw twin was concurrency.
        concurrent_only = (
            form == "residualised" and verdict == "SCREEN-WEAK" and bool(r.get("powered"))
            and twin is not None and str(twin.get("verdict")) == "SCREEN-INTERESTING"
        )
        base = {
            "cell": r.get("cell"), "construction": r.get("construction"),
            "bar_ms": r.get("bar_ms"), "ic": r.get("ic"),
            "n": r.get("n"), "n_eff": r.get("n_eff"),
            # BOTH floors, because a kill without one is unfalsifiable and a kill quoting only the
            # family-wise one understates what the sample could actually see.
            "detection_floor_ic_unadjusted": r.get("min_detectable_ic"),
            "detection_floor_ic_family_wise": floor,
            "type2_label": r.get("type2_label"),
        }
        if concurrent_only and twin is not None:
            graveyard.append({
                **base, "form": "raw-vs-residualised", "verdict": "CONCURRENT-ONLY",
                "raw_ic": twin.get("ic"),
                "raw_same_period_corr": twin.get("same_period_corr"),
                "reason": ("the raw state scored and the orthogonalised state did not: the "
                           "apparent forecast was a restatement of the bar that had already "
                           "happened. This is the class's pre-registered null, confirmed."),
            })
        elif verdict in _KILL_VERDICTS and bool(r.get("powered")):
            graveyard.append({
                **base, "form": r.get("form"), "verdict": verdict,
                "same_period_corr": r.get("same_period_corr"),
                "residual_ic": r.get("residual_ic"),
                "reason": _KILL_REASONS[verdict],
            })
    return survivors, graveyard


def build_report(rows: list[dict[str, Any]], *, alignment: Alignment, files_read: int,
                 files_on_disk: int, cells_screened: int, cells_on_disk: int) -> dict[str, Any]:
    scored = [r for r in rows if isinstance(r.get("ic"), (int, float))]
    n_family = max(PREREGISTERED_FAMILY, len(scored))
    _significance(scored, n_family=n_family)
    pairs = _type2(scored, n_family=n_family)
    survivors, graveyard = classify(scored)
    # The power headline is a statement about this run's RECORDED NEGATIVES. A survivor is not one
    # of them, and counting it as an underpowered null would understate the run twice over.
    surv_keys = {(s["cell"], s["construction"], s["bar_ms"]) for s in survivors}
    costs = [c for r, c in pairs
             if not (str(r.get("form")) == "residualised"
                     and (r.get("cell"), r.get("construction"), r.get("bar_ms")) in surv_keys)]

    tally: dict[str, int] = {}
    for r in rows:
        v = str(r.get("verdict", "?"))
        tally[v] = tally.get(v, 0) + 1

    powered = sum(1 for r in scored if bool(r.get("powered")))
    desk = headline(costs) if costs else None
    return {
        "schema_version": SCHEMA_VERSION,
        "generated_utc": datetime.now(tz=UTC).isoformat(),
        "script": "scripts/screen_orderbook_state.py",
        "status": "SCREENED",
        "stage": "A (zero promotion authority)",
        "mechanism_class": MECHANISM_CLASS,
        "pre_registration": pre_registration(alignment),
        "files_read": files_read, "files_on_disk": files_on_disk,
        "cells_screened": cells_screened, "cells_on_disk": cells_on_disk,
        "hypotheses": len(rows), "scored": len(scored),
        "family_size_charged": n_family,
        "family_z_critical": round(float(critical_z(DEFAULT_ALPHA, n_family, two_sided=True)), 4),
        "declared_effects": list(DECLARED_CORRELATION_EFFECTS),
        # THE NULL'S CREDENTIALS, ON BOTH BASES, EACH NAMED. Reported even -- especially -- when
        # there are no survivors: it is the difference between "we looked and it is not there" and
        # "we could not have seen it". The two counts below are NOT in conflict and the key names
        # say why: the first is the UNADJUSTED (N=1) floor the harness's own SCREEN-WEAK /
        # SCREEN-UNDERPOWERED split encodes and the basis on which a cell may be graveyarded; the
        # second is the floor at the family-wise charge, i.e. the bar a FIND had to clear. A cell
        # routinely clears the first and not the second, and that gap is the price of 30 cells.
        "powered_cells_unadjusted": powered,
        "power_headline_at_family_charge": (
            desk.summary() if desk is not None else "no scored cell to power-label"),
        "power_counts_at_family_charge": {
            "negatives": desk.n_negatives if desk is not None else 0,
            "powered": desk.n_powered if desk is not None else 0,
            "underpowered": desk.n_underpowered if desk is not None else 0,
            "indeterminate": desk.n_indeterminate if desk is not None else 0,
        },
        # A cell the harness liked that the multiplicity charge removed. Reported explicitly so a
        # reader is never left comparing a SCREEN-INTERESTING tally against an empty survivor list
        # and guessing which gate intervened.
        "interesting_but_failed_multiplicity": sum(
            1 for r in scored if str(r.get("verdict")) == "SCREEN-INTERESTING"
            and not bool(r.get("clears_family_wise"))),
        "tally": tally,
        "survivors": survivors,
        "graveyard": graveyard,
        "rows": rows,
        "note": (
            "ZERO SURVIVORS IS THE EXPECTED AND PUBLISHABLE OUTCOME. What makes it knowledge "
            "rather than silence is the power column: a POWERED-NEGATIVE cell looked and found "
            "nothing, an UNDERPOWERED cell could not have seen anything and refutes NOTHING. Only "
            "the first is graveyard-grade. A survivor earns a forward clock and never a cent."
        ),
        "authority": "NONE -- Stage A. Nothing here promotes, sizes, or writes a clock file.",
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Stage-A screen: order-book microstructure state")
    ap.add_argument("--files", type=int, default=FILE_BUDGET,
                    help="partition budget for one run")
    ap.add_argument("--decision-lag-ms", type=int, default=0,
                    help="latency charged before the target print is taken; 0 is the optimistic "
                         "upper bound the pre-registration declares")
    ap.add_argument("--out", type=Path, default=REPORT)
    a = ap.parse_args(argv)

    alignment = Alignment(bar_ms=HORIZONS_MS[0], decision_lag_ms=int(a.decision_lag_ms))
    out_path = Path(a.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    files = tape_files()
    if not files:
        report = not_readable_here(alignment)
        out_path.write_text(json.dumps(report, indent=1, default=str), "utf-8")
        print(f"orderbook-state: NOT-READABLE-HERE -- {len(report['missing_paths'])} missing "
              f"path(s) under {_rel(MOAT)}")
        for p in report["missing_paths"]:
            print(f"    MISSING {p}")
        print("  the recorders are the blocker; no synthetic tape is generated and no result is "
              "reported")
        return 0

    grid = cells(files)
    budget = int(a.files)
    rows: list[dict[str, Any]] = []
    used = 0
    for key, cfiles in grid.items():
        if budget <= 0:
            break
        take = cfiles[:budget]
        budget -= len(take)
        used += 1
        recs: list[dict[str, Any]] = []
        for f in take:
            recs.extend(read_partition(f))
        rows.extend(screen_cell(f"{key[0]}:{key[1]}@{key[2]}", recs,
                                decision_lag_ms=int(a.decision_lag_ms)))

    report = build_report(rows, alignment=alignment,
                          files_read=int(a.files) - budget, files_on_disk=len(files),
                          cells_screened=used, cells_on_disk=len(grid))
    out_path.write_text(json.dumps(report, indent=1, default=str), "utf-8")

    print(f"orderbook-state: {report['hypotheses']} pre-registered hypotheses over "
          f"{used} cell(s), {report['files_read']}/{len(files)} partitions")
    print(f"  family charged {report['family_size_charged']} at alpha {DEFAULT_ALPHA} "
          f"(z_crit {report['family_z_critical']}), "
          f"powered cells {report['powered_cells_unadjusted']} unadjusted / "
          f"{report['power_counts_at_family_charge']['powered']} at the family charge")
    for v, c in sorted(report["tally"].items(), key=lambda kv: -kv[1]):
        print(f"  {v:<24} {c}")
    if report["survivors"]:
        print(f"  SURVIVORS ({len(report['survivors'])}) -- residualised, powered, family-wise:")
        for s in report["survivors"]:
            print(f"    {s['cell']}:{s['construction']}@{s['bar_ms']}ms IC={s['ic']} "
                  f"(needed {s['ic_needed_family_wise']}), raw twin same-corr "
                  f"{s['raw_twin_same_period_corr']}")
    else:
        print("  NO SURVIVORS -- the expected outcome and a publishable one"
              + (f" ({report['interesting_but_failed_multiplicity']} cell(s) cleared the harness "
                 "and were removed by the multiplicity charge)"
                 if report["interesting_but_failed_multiplicity"] else ""))
    if report["graveyard"]:
        print(f"  GRAVEYARD-GRADE NEGATIVES ({len(report['graveyard'])}) -- each with its reason "
              "and detection floor")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
