#!/usr/bin/env bash
# Size the heavy-research memory budget to the MACHINE, not to a constant somebody typed once.
#
# WHY. `quant-heavy.slice` carried MemoryHigh=2400M/MemoryMax=2800M, chosen on 2026-09-01 for a
# 4GB host. Two units -- quant-nightly-catchup and quant-recertify-canon -- carried 3G/4G of their
# own and were not in the slice at all, so on a 4GB box either could take every page on the
# machine. When that happens the global OOM killer picks the LARGEST process it can see, which
# here is routinely the dashboard server or cloudflared rather than the organ that overran: the
# desk goes dark and the log blames a process that behaved perfectly.
#
# A CONSTANT IS THE BUG, NOT THE NUMBER. Any figure written here is correct for exactly one
# machine and silently wrong the moment the desk moves or the plan is resized -- and this desk has
# now done both. A budget derived from /proc/meminfo is right on a 4GB box, right after a resize
# to 8GB, and right on whatever it runs on next, with no edit and nothing to remember.
#
# THE SHAPE OF THE SPLIT. Research gets a fraction of total RAM, never all of it: the trading
# path, the dashboard, the tunnel and the OS need headroom that must not be borrowable. MemoryHigh
# THROTTLES (reclaim, slow down, still finish) and MemoryMax KILLS, so High sits meaningfully
# below Max -- a heavy run should get slower under pressure, not die and be retried forever.
#
#   ./ops/size_memory_budget.sh            write the drop-in and reload
#   ./ops/size_memory_budget.sh --check    print what it would set, change nothing
set -uo pipefail

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

#: Share of total RAM the heavy research slice may hold. 60% leaves the gateway, the dashboard,
#: cloudflared, sshd and the kernel a floor that no research organ can take, which is the whole
#: point -- the desk being visible matters more than a sweep finishing an hour sooner.
HIGH_PCT="${QUANT_HEAVY_HIGH_PCT:-60}"
#: The hard ceiling. The gap between the two is the throttling band.
MAX_PCT="${QUANT_HEAVY_MAX_PCT:-70}"

kb="$(awk '/^MemTotal:/ {print $2}' /proc/meminfo 2>/dev/null)"
if [ -z "${kb:-}" ]; then
  echo "cannot read /proc/meminfo -- refusing to guess a memory budget" >&2
  exit 2
fi
total_mb=$(( kb / 1024 ))
high_mb=$(( total_mb * HIGH_PCT / 100 ))
max_mb=$(( total_mb * MAX_PCT / 100 ))

# A FLOOR, because a percentage of a very small box is a budget nothing can run in -- and a slice
# that strangles every organ is indistinguishable from a broken desk. Below this the honest answer
# is that the host is too small, said out loud rather than encoded as mysterious slowness.
if [ "$high_mb" -lt 512 ]; then
  echo "MemTotal is only ${total_mb}MB: a 60% research budget is ${high_mb}MB, below the 512MB" >&2
  echo "floor at which these organs can run at all. Refusing to write a budget that cannot work." >&2
  exit 2
fi

printf 'host MemTotal : %s MB\n' "$total_mb"
printf 'slice budget  : MemoryHigh=%sM  MemoryMax=%sM  (%s%% / %s%%)\n' \
       "$high_mb" "$max_mb" "$HIGH_PCT" "$MAX_PCT"

if [ "$CHECK" = 1 ]; then
  echo "(--check: nothing written)"
  exit 0
fi

dir="$HOME/.config/systemd/user/quant-heavy.slice.d"
mkdir -p "$dir"
# NAMED TO SORT LAST, AND THE OLD NAME REMOVED. systemd applies drop-ins in lexical order and the
# LAST one wins, so a file called 10-sized.conf loses to any 20-*.conf or 90-*.conf already on the
# box. Measured on the 8GB host 2026-09-06: this script wrote MemoryHigh=4647M and systemd went on
# enforcing 1800M/2200M from another drop-in -- the file was written, the message said so, and
# nothing was actually changed. A setting that is written but not in force is the most misleading
# state available: it reads exactly like success.
rm -f "$dir/10-sized.conf"
for competing in "$dir"/*.conf; do
  [ -e "$competing" ] || continue
  case "$(basename "$competing")" in
    90-sized.conf) ;;
    *) if grep -qE '^\s*Memory(High|Max)=' "$competing" 2>/dev/null; then
         echo "  note: $(basename "$competing") also sets a memory limit; this file sorts after it and wins"
       fi ;;
  esac
done
cat > "$dir/90-sized.conf" <<EOF
# GENERATED by ops/size_memory_budget.sh -- do not hand-edit; re-run the script instead.
# Derived from this host's MemTotal (${total_mb}MB) at $(date -u +%FT%TZ), at ${HIGH_PCT}%/${MAX_PCT}%.
# A hand-typed figure here is correct for one machine and silently wrong after any resize or move.
[Slice]
MemoryHigh=${high_mb}M
MemoryMax=${max_mb}M
MemorySwapMax=0
EOF
echo "wrote $dir/90-sized.conf"

systemctl --user daemon-reload 2>/dev/null && echo "systemd reloaded" \
  || echo "could not reload the user manager -- run: systemctl --user daemon-reload" >&2

# VERIFY, DO NOT MERELY REPORT. A written file is not an applied setting: it can lose to a
# later-sorting drop-in, and a slice no unit has joined enforces nothing at all. The first version
# printed the in-force numbers next to the intended ones and left the reader to notice they
# differed -- which is how 1800M went on being enforced under a message announcing 4647M.
in_high="$(systemctl --user show quant-heavy.slice -p MemoryHigh --value 2>/dev/null)"
in_max="$(systemctl --user show quant-heavy.slice -p MemoryMax --value 2>/dev/null)"
if [ -z "${in_high:-}" ]; then
  echo "  note: the slice is not loaded yet -- it applies when a unit declaring" \
       "Slice=quant-heavy.slice next starts"
  exit 0
fi
want_high=$(( high_mb * 1024 * 1024 ))
want_max=$(( max_mb * 1024 * 1024 ))
printf '  in force      : MemoryHigh=%s  MemoryMax=%s\n' "$in_high" "$in_max"
if [ "$in_high" = "$want_high" ] && [ "$in_max" = "$want_max" ]; then
  echo "  VERIFIED: what systemd enforces matches what was written."
  exit 0
fi
cat >&2 <<EOF
  MISMATCH: systemd is enforcing MemoryHigh=${in_high} MemoryMax=${in_max}, not the
  ${want_high}/${want_max} just written. Another drop-in or the unit file itself is winning.
  Look at:  systemctl --user cat quant-heavy.slice
  The budget on this host is NOT what this script reports; do not treat it as applied.
EOF
exit 1
