"""EVENT LABELS -- and the three-state answer that keeps a half-calendar from lying.

The confound: the failed-breakout and OI-divergence studies cannot tell a cascade caused by a
scheduled macro print from one generated by the book's own leverage. Scheduled events cluster the
biggest moves, so an uncontrolled study preferentially samples them and its "mechanism" is partly
a release detector wearing a microstructure name.

THE DANGER THIS MODULE INTRODUCES IS LARGER THAN THE ONE IT REMOVES, which is what most of this
file tests. An incomplete calendar used to exclude event windows removes a BIASED subset and
leaves the researcher believing the remainder is clean. With no calendar you know you have not
controlled for events; with a half-calendar you think you have.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime, timedelta

from libs.research.event_calendar import (
    Calendar,
    Event,
    coverage_note,
    label,
    load,
    partition,
)

_T0 = datetime(2024, 4, 20, tzinfo=UTC)          # a seeded halving


def _cal(**kw) -> Calendar:
    ev = kw.pop("events", (Event(_T0, "btc_halving"),))
    return Calendar(events=ev,
                    covered_from=kw.pop("frm", _T0 - timedelta(days=30)),
                    covered_to=kw.pop("to", _T0 + timedelta(days=30)),
                    kinds=tuple(dict.fromkeys(e.kind for e in ev)),
                    complete_for=kw.pop("complete_for", ()))


def test_UNCOVERED_IS_NOT_EVENT_FREE() -> None:
    """THE LOAD-BEARING TEST. A timestamp outside the calendar's span must return None (cannot
    say), never "" (no event). Collapsing those two is how a period nobody catalogued gets treated
    as clean, biasing the exclusion in the direction that flatters the result."""
    cal = _cal()
    inside_no_event = _T0 + timedelta(days=10)
    outside = _T0 + timedelta(days=400)
    got = label(cal, [inside_no_event, outside])
    assert got[0] == "", "covered and quiet must be an empty label, not None"
    assert got[1] is None, "outside the span must be NOT MEASURED, not 'no event'"


def test_AN_EVENT_IN_WINDOW_IS_LABELLED_WITH_ITS_KIND() -> None:
    cal = _cal()
    assert label(cal, [_T0 + timedelta(minutes=30)], window_min=60)[0] == "btc_halving"
    assert label(cal, [_T0 + timedelta(minutes=90)], window_min=60)[0] == ""


def test_THE_WINDOW_IS_SYMMETRIC() -> None:
    """A cascade can begin before a scheduled print (positioning ahead of it) as easily as after."""
    cal = _cal()
    assert label(cal, [_T0 - timedelta(minutes=30)], window_min=60)[0] == "btc_halving"


def test_AN_EMPTY_CALENDAR_SAYS_NOTHING_RATHER_THAN_NO_EVENT() -> None:
    """A calendar that failed to load must not silently declare the entire history event-free."""
    empty = Calendar(events=(), covered_from=None, covered_to=None, kinds=())
    assert label(empty, [_T0, _T0 + timedelta(days=1)]) == [None, None]


def test_PARTITION_KEEPS_UNCOVERED_AS_ITS_OWN_BUCKET() -> None:
    """Three buckets, not two. An 'endogenous sample' that quietly absorbed uncovered bars is not
    clean, it is unexamined."""
    cal = _cal()
    ts = [_T0, _T0 + timedelta(days=10), _T0 + timedelta(days=400)]
    parts = partition(cal, ts)
    assert parts["event"] == [0]
    assert parts["endogenous"] == [1]
    assert parts["uncovered"] == [2]


def test_THE_NOTE_WARNS_WHEN_COVERAGE_IS_PARTIAL() -> None:
    """The warning has to reach the human reading the result, not sit in a dataclass field."""
    cal = _cal()
    parts = partition(cal, [_T0 + timedelta(days=400), _T0 + timedelta(days=10)])
    note = coverage_note(cal, parts)
    assert "UNCOVERED" in note and "BIASED subset" in note


def test_THE_NOTE_REFUSES_THE_PHRASE_EXCLUDING_MACRO_EVENTS_WITHOUT_A_COMPLETENESS_CLAIM() -> None:
    """`complete_for` is the operator's assertion that a kind is listed EXHAUSTIVELY. With none
    declared, no result may be described as having excluded macro events -- it excluded the events
    that happened to be listed, which is a different and much weaker statement."""
    note = coverage_note(_cal(), partition(_cal(), [_T0 + timedelta(days=5)]))
    assert "NOTHING is claimed exhaustive" in note


def test_A_COMPLETENESS_CLAIM_IS_CARRIED_THROUGH() -> None:
    cal = _cal(complete_for=("cpi", "fomc"))
    note = coverage_note(cal, partition(cal, [_T0 + timedelta(days=5)]))
    assert "cpi" in note and "NOTHING is claimed exhaustive" not in note


def test_STRUCTURAL_EVENTS_LOAD_WITHOUT_ANY_FILE() -> None:
    """Halvings are block-height determined and independently checkable, so they are the only
    events safe to hardcode. Macro dates written from memory would manufacture exactly the false
    completeness this module warns about."""
    cal = load(ROOT_MISSING := __import__("pathlib").Path("/nonexistent/x.json"))
    assert ROOT_MISSING  # silence lint on the walrus
    assert len(cal) == 4
    assert cal.kinds == ("btc_halving",)
    assert cal.complete_for == (), "a missing file must claim nothing exhaustive"


def test_A_MALFORMED_ROW_IS_SKIPPED_NOT_GUESSED(tmp_path) -> None:  # type: ignore[no-untyped-def]
    """A row with no timestamp cannot be placed. Inventing one would put a fake event on the
    calendar, which mislabels a clean window as contaminated -- worse than omitting it."""
    p = tmp_path / "cal.json"
    p.write_text(json.dumps({
        "covered_from": "2024-01-01T00:00:00+00:00",
        "covered_to": "2024-12-31T00:00:00+00:00",
        "complete_for": ["cpi"],
        "events": [{"ts": "2024-06-12T12:30:00+00:00", "kind": "cpi", "source": "bls"},
                   {"kind": "cpi"},                      # no ts
                   {"ts": "not-a-date", "kind": "cpi"}],
    }), "utf-8")
    cal = load(p, include_structural=False)
    assert len(cal) == 1
    assert cal.complete_for == ("cpi",)


def test_COVERAGE_NEVER_EXTENDS_PAST_THE_LAST_EVENT_BY_DEFAULT(tmp_path) -> None:  # type: ignore[no-untyped-def]
    """With no declared window the span falls back to the events' own range and no further. A
    calendar claiming coverage past its last entry would report 'no event' for every later bar."""
    p = tmp_path / "c.json"
    p.write_text(json.dumps({"events": [
        {"ts": "2024-06-12T12:30:00+00:00", "kind": "cpi"}]}), "utf-8")
    cal = load(p, include_structural=False)
    assert cal.covered_to == datetime(2024, 6, 12, 12, 30, tzinfo=UTC)
    assert label(cal, [datetime(2025, 1, 1, tzinfo=UTC)])[0] is None
