"""THE DISCOVERY -> LIVE BRIDGE -- the module existed and nothing called it.

`libs/research/live_ladder.py` carried the arithmetic and had ZERO consumers, which is the same
defect as a generator that emits 898,560 candidates with nothing able to run one: a ladder nobody
calls is a document. These tests fence the bridge, and most of them are about the two rungs that
are easy to get backwards -- shadow (free, starts the clock today) and the clip floor below which a
live record measures fees rather than the strategy.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest
import scripts.run_live_ladder as RL


def _write(p: Path, obj: object) -> Path:
    p.write_text(json.dumps(obj), "utf-8")
    return p


# ------------------------------------------------------------------ the shadow rung


def test_A_SURVIVOR_WITH_NO_FORWARD_RECORD_IS_OWED_A_SHADOW_START(
        tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """THE WHOLE POINT OF THE BRIDGE. Shadow costs nothing and starts the forward clock today; the
    clock is the one input that cannot be bought later, so a Stage-A survivor sitting in a queue is
    pure waste."""
    sweep = _write(tmp_path / "sweep.json",
                   {"survivors": [{"key": ["cat", "ratio", "1h", "all", "funding", "oi"]}]})
    out = tmp_path / "rep.json"
    monkeypatch.setattr(sys, "argv", ["run_live_ladder.py", "--sweep", str(sweep),
                                      "--records", str(tmp_path / "none.json"), "--out", str(out)])
    assert RL.main() == 0
    rep = json.loads(out.read_text())
    assert rep["to_shadow"] == ["cat|ratio|1h|all|funding|oi"]
    assert rep["stage_a_survivors"] == 1


def test_A_SURVIVOR_THAT_ALREADY_HAS_A_RECORD_IS_NOT_RE_SHADOWED(
        tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    key = ["cat", "ratio", "1h", "all", "funding", "oi"]
    sweep = _write(tmp_path / "sweep.json", {"survivors": [{"key": key}]})
    recs = _write(tmp_path / "recs.json", {"records": [
        {"name": "|".join(key), "n_trades": 500, "mean_bps": 2.0, "sd_bps": 20.0,
         "clip_notional": 5000}]})
    out = tmp_path / "rep.json"
    monkeypatch.setattr(sys, "argv", ["run_live_ladder.py", "--sweep", str(sweep),
                                      "--records", str(recs), "--out", str(out)])
    assert RL.main() == 0
    rep = json.loads(out.read_text())
    assert rep["to_shadow"] == [] and len(rep["verdicts"]) == 1


# ------------------------------------------------------------- the informative-clip floor


def test_BELOW_THE_INFORMATIVE_CLIP_A_LIVE_TEST_MEASURES_FEES() -> None:
    """The floor that is not obvious. Minimum notionals, tick rounding and the crossed spread do
    not scale down, so at a small enough size the drag exceeds any plausible edge -- and the
    natural reading of that measurement is 'retire it', generated by costs rather than strategy."""
    floor = RL.min_informative_clip()
    assert floor > 0
    assert RL.size_cost_penalty(floor) <= RL.DRAG_BUDGET * RL.MIN_INTERESTING_BPS
    # and a clip an order of magnitude smaller is NOT informative
    assert RL.size_cost_penalty(floor / 10) > RL.DRAG_BUDGET * RL.MIN_INTERESTING_BPS


def test_A_TOO_SMALL_CLIP_IS_FLAGGED_ON_THE_VERDICT(
        tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Going live tiny feels like progress while producing an uninformative number. The report has
    to say so beside the verdict, or the reader acts on the number."""
    recs = _write(tmp_path / "recs.json", {"records": [
        {"name": "tiny", "n_trades": 400, "mean_bps": 3.0, "sd_bps": 20.0, "clip_notional": 5.0},
        {"name": "big", "n_trades": 400, "mean_bps": 3.0, "sd_bps": 20.0,
         "clip_notional": 50_000.0},
    ]})
    out = tmp_path / "rep.json"
    monkeypatch.setattr(sys, "argv", ["run_live_ladder.py", "--records", str(recs),
                                      "--sweep", str(tmp_path / "none.json"), "--out", str(out)])
    assert RL.main() == 0
    verdicts = json.loads(out.read_text())["verdicts"]
    flags = {v["name"]: v["clip_below_informative_floor"] for v in verdicts}
    assert flags == {"tiny": True, "big": False}


def test_THE_REPORT_EXPLAINS_WHY_SHADOW_IS_THE_HONEST_RUNG_UNDER_THE_FLOOR(
        tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    out = tmp_path / "rep.json"
    monkeypatch.setattr(sys, "argv", ["run_live_ladder.py", "--records", str(tmp_path / "a.json"),
                                      "--sweep", str(tmp_path / "b.json"), "--out", str(out)])
    RL.main()
    note = json.loads(out.read_text())["min_informative_note"]
    assert "mostly measures fees" in note and "SHADOW" in note


# ------------------------------------------------------------------- honest refusal


def test_WITH_NOTHING_TO_LADDER_IT_BLOCKS_RATHER_THAN_REPORTING_AN_EMPTY_LADDER(
        tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """No records and no survivors is UNMEASURED, not a ladder with nothing on it -- and the two
    read completely differently to whoever opens the artifact next."""
    out = tmp_path / "rep.json"
    monkeypatch.setattr(sys, "argv", ["run_live_ladder.py", "--records", str(tmp_path / "a.json"),
                                      "--sweep", str(tmp_path / "b.json"), "--out", str(out)])
    assert RL.main() == 0
    rep = json.loads(out.read_text())
    assert rep["verdict"].startswith("BLOCKED")
    assert "UNMEASURED, not an empty ladder" in rep["reason"]
    assert "Gate-0" in rep["reason"] and "GAP #91" in rep["reason"]


def test_A_MALFORMED_RECORD_IS_SKIPPED_NEVER_DEFAULTED_INTO_EXISTENCE() -> None:
    """A row missing its trade count defaulted to zero would become an UNDERPOWERED verdict about a
    strategy that has no record at all -- a verdict invented from a parse failure."""
    rows = RL.records_from({"records": [
        {"name": "ok", "n_trades": 10, "mean_bps": 1.0, "sd_bps": 2.0},
        {"name": "no_trades", "mean_bps": 1.0, "sd_bps": 2.0},
        {"name": "junk", "n_trades": "many", "mean_bps": 1.0, "sd_bps": 2.0},
    ]})
    assert [r.name for r in rows] == ["ok"]


def test_AN_ABSENT_SWEEP_YIELDS_NO_SURVIVORS_RATHER_THAN_RAISING() -> None:
    assert RL.survivors_from(None) == []
    assert RL.survivors_from({"survivors": []}) == []


def test_THE_SCRIPT_PLACES_NOTHING_AND_SAYS_SO(tmp_path: Path,
                                               monkeypatch: pytest.MonkeyPatch) -> None:
    """Arming live trading is the principal's act; the dead-man rail is never touched."""
    out = tmp_path / "rep.json"
    monkeypatch.setattr(sys, "argv", ["run_live_ladder.py", "--records", str(tmp_path / "a.json"),
                                      "--sweep", str(tmp_path / "b.json"), "--out", str(out)])
    RL.main()
    assert "places no orders" in json.loads(out.read_text())["authority"]
    src = Path("scripts/run_live_ladder.py").read_text("utf-8")
    for token in ("place_market", "place_order", "binance", "api_key"):
        assert token not in src.lower(), f"the bridge reached toward an order path: {token!r}"
